### ISSUE TITLE
onAnimationEnd event not firing

### ISSUE THREAD

**Issue by tholman** [preactjs/preact#1589]
Perhaps a regression with preact 10, or perhaps intended behavior?

Prior to 10 `onAnimationEnd` would fire the end event when an animation ends... which no longer happens. 

Test case of it failing to alert here https://codesandbox.io/s/71p06y27xj ~ temp (or real) fix was to use lowercase onanimationend

**Comment by JoviDeCroock** [comment]
Hey, thanks for the good reproduction I have debugged this a bit and it seems that this check: https://github.com/developit/preact/blob/master/src/diff/props.js#L76 returns false, that's why the lowercase one works but the uppercase one does not. Trying to find out why animationend is not present in a dom node.

**Comment by cristianbote** [comment]
Here's an idea, what if we do a lookup on the `window` as well? 

```js
name = ((nameLower in dom) || (nameLower in window) ? nameLower : name).substring(2);
```

Since `animation`, `transition` are part of the global event handler (https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers) we could query that. Not sure if it's the best approach, but I guess that path for event handling is not accessible for a non-windowed environment.

What do you think?

**Comment by JoviDeCroock** [comment]
@cristianbote that's a great idea, I had a PR ready with a different approach but yours will add less bytes and support more diverse cases aswell.

**Comment by gpoitch** [comment]
Just bit by this not working again upgrading from beta.1 to latest X.  Looks like the fix was reverted in #1631.  Is just using lowercase props the final solution or should this be reopened?

**Comment by JoviDeCroock** [comment]
Fix seems to still be present https://github.com/preactjs/preact/blob/master/compat/src/index.js#L273

**Comment by gpoitch** [comment]
@JoviDeCroock Here's the original sandbox from this issue simply updated to 10.0.4 showing that it doesn't work: https://codesandbox.io/s/reverent-stallman-62ehj

Also note that it doesn't work in Chrome but works in Safari.

**Comment by JoviDeCroock** [comment]
This works with `preact/compat`, did it ever work with `preact` pure?

**Comment by gpoitch** [comment]
I'm only ever working with pure preact. It worked in 8 and 10.0.0-beta.1 (which is when the original fix was in).  Looks like it doesn't work in any other 10 releases.  Fine with just using lowercase if that's the final ruling from #1631, although it is an oddity that would be cool to fix.

**Comment by JoviDeCroock** [comment]
Let me see what changed in beta.2 then, then it stops working right?

**Comment by gpoitch** [comment]
Correct. https://github.com/preactjs/preact/compare/e206b07...22a028f
I see the test case was downcased.

**Comment by JoviDeCroock** [comment]
Oh, I understand onAnimationEnd does not exist on the dom so only lower case will work, see https://github.com/preactjs/preact/pull/1631/files#diff-642a704212e8abfc3d854f17a1aaacbeL65

**Comment by JoviDeCroock** [comment]
Updating this reproduction to latest makes it work
