### ISSUE TITLE
onTransitionEnd stopped working

### ISSUE THREAD

**Issue by cloakedninjas** [preactjs/preact#1662]
Have noticed when aliasing preact 10.beta.1 for an existing react app, when a state change occurred and that variable was passed into a child prop, the child component is removed from the DOM and so `transitionEnd` events don't trigger.

The React app doesn't use CSSTransition or others libs.

Is this a bug? Or is there something special I need to do?

**Comment by marvinhagemeister** [comment]
@cloakedninjas Can you share a [codesandbox](https://codesandbox.io) or a repo where the issue can be reproduced? It helps us tremendously in fixing bugs :+1:

**Comment by robertknight** [comment]
This is an expected change related to the discussion in https://github.com/preactjs/preact/pull/1618 and https://bugs.chromium.org/p/chromium/issues/detail?id=961193.

The short version is that for the moment, you need to use `ontransitionend` and `onanimationend` in Preact rather than the capitalised versions. This is due to the way that Preact tests whether an event name exists, but the name needs to be lower-cased.

I wonder whether we ought to paper over this browser difference in `preact/compat`.

**Comment by cloakedninjas** [comment]
Thanks for update, have been busy so yet to look back into this issue, I'll try and change the casing and report back.

Also 👍 for `preact/compat` to take care of this, saving dependants creating duped attributes

**Comment by marvinhagemeister** [comment]
We now smooth over the naming difference in compat :tada:
