### ISSUE TITLE
Docs: Fragments not documented?

### ISSUE THREAD

**Issue by IngwiePhoenix** [preactjs/preact#1670]
I just wanted to make sure I did not overlook this. :)

I was scrolling across the README and the official website's documentation, but could not find any documentation regarding Fragments - or what other features version 10 and it's betas have introduced thus far.

I want to switch to Preact, and since my app itself is in an early stage, I don't actually mind using the Beta for the time being.

Kind regards,
Ingwie

**Comment by marvinhagemeister** [comment]
That's awesome, thanks for your interest in Preact 👍 The reasoning behind is that X is still in beta. The official documentation has only covered the latest stable release so far which is why any mention of `Fragments` is missing. For now the release logs are the best place to read about any new features Preact X brings to the table 💯
