### ISSUE TITLE
`options._commit` is called on child although parent commit is in progress

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact#1736]
While working on the new devtools adapter in #1549 , I came across an issue where `options._commit` is called on a child although there is a pending commit already in progress on a parent. This can be reproduced with the following snippet ([codesandbox](https://codesandbox.io/s/optionscommit-6bgox) link for the lazy):

```jsx
import { h, render, Component, options } from "preact";

let i = 0;
// options.commit, should only be called once
options.__c = vnode => console.log(i++, vnode);

class App extends Component {
  componentDidMount() {
    this.forceUpdate();
  }
  render() {
    return <div>foo</div>;
  }
}

render(<App />, document.getElementById("app"));
```

This pattern may seem strange, but it's actually something that is used in `mobx-react`. It can be observed with our people demo app when you navigate to `/people` (make sure the detail view is blank via a reload) and then click on a person name in the left to mount the detail view.

**Comment by JoviDeCroock** [comment]
All right just thinking about this so the forceUpdate should be added to the pending commit right?

**Comment by andrewiggins** [comment]
I think this may point to a difference in how React's `forceUpdate` works and ours. I believe React's `forceUpdate` schedules an update to happen after the current render/commit phase (sans any optimizations they may apply). If that's true, their `forceUpdate` behaves more like our `setState({})`.

Our `forceUpdate` synchronously does a diff right in the middle of whatever call stack it is in.

Perhaps we should change our `forceUpdate`  to call `setState({})` and inline the current forceUpdate implementation inside of the `processQueue` function? Might save us some difficult compat issues down the road (and also makes thinking about `forceUpdate` easier since it behaves just like `setState` instead of doing something wildly different)

I used this codesandbox to test my theory: https://codesandbox.io/s/gallant-hellman-4cfkk. Notice how in React `=== Parent cDM ===` is logged before the second `ForceUpdate.render` (implying React schedules the forceUpdate to occur after the current diff stack) whereas in Preact `=== Parent.cDM ===` is logged after the second `ForceUpdate.render`.

**Comment by JoviDeCroock** [comment]
That change would imply that we would have to change our way of testing I assume, since if we move to setState we would have to call `rerender()` everytime we use `forceUpdate`

**Comment by jeremy-coleman** [comment]
would just wrapping with promise.resolve().then(()=>forceUpdate()) fix the timing? It would still be sync, but im pretty sure it would cause forceUpdate to run after cdm

**Comment by marvinhagemeister** [comment]
This is fixed in `master` with the first release of Preact X. Any components where `forceUpdate` was called on now participate in the same update queue :tada:
