### ISSUE TITLE
Namespaced attributes in 8.x

### ISSUE THREAD

**Issue by jschill** [preactjs/preact#1870]
From what I understand they should be supported, but when i'm using xmlSpace, xmlnsXlink or xlinkHref they dont look replaced in the console. Or is the browser pulling my leg?

https://jsfiddle.net/0yh4z6tj/

**Comment by marvinhagemeister** [comment]
Namespaced attributes are pretty rare and have been officially deprecated for a while and may be removed from browsers in the future. Because of that we don't support them in Preact. You can easily add support for them in your project by adding an `options.vnode` hook.

```js
import { options } from "preact";

options.vnode = vnode => {
  const transform = {
    'xlinkActuate': 'xlink:actuate',
    'xlinkArcrole': 'xlink:arcrole',
    'xlinkHref': 'xlink:href',
    'xlinkRole': 'xlink:role',
    'xlinkShow': 'xlink:show',
    'xlinkTitle': 'xlink:title',
    'xlinkType': 'xlink:type',
    'xmlBase': 'xml:base',
    'xmlLang': 'xml:lang',
    'xmlSpace': 'xml:space',
    'xmlnsXlink': 'xmlns:xlink',
  };

  for (const prop in vnode.props) {
    if (transform[prop]) {
       vnode.props[transform[prop]] = vnode.props[prop];
       delete vnode.props[prop];
    }
  }
}
```

Relevant links on MDN:

- *deprecated* [xlink:href](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)
- *deprecated* [xml:space](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space)

**Comment by jschill** [comment]
@marvinhagemeister Thanks! And thanks for the workaround.

I guess what confused me is that in the `SVGAttributes` interface there are props for those, so I thought they were supported.

https://github.com/preactjs/preact/blob/7a3535fb8e9dbed0714ffc7b53f5981dfe5c6366/src/jsx.d.ts#L263

**Comment by marvinhagemeister** [comment]
@jschill That's a good point :+1: I don't really remember the reasons, but my guess is that we added them so that TS users have a chance at setting them because extending jsx types is always finicky...
