### ISSUE TITLE
setState performance Preact VS React benchmark: different behaviour in production build

### ISSUE THREAD

**Issue by avkonst** [preactjs/preact#1891]
I have attempted to replicate [this](https://hookstate.netlify.com/performance-demo-large-table) performance benchmark for [Hookstate](https://github.com/avkonst/hookstate) using Preact.  It uses setState extensively. The benchmark code for Preact + Hookstate is committed [here](https://github.com/avkonst/hookstate/tree/master/experimental/preact).

**Good news:**
(according to the benchmark)
- Preact in development mode is about 5 times faster than React in development mode
- Preact in development mode is about 30% faster than React in production mode
- Preact in production mode is about 75% faster than React in production mode. Note: I have put explicit workaround for the problem described below in order to get the stats for production run - just uncomment every line with 'workaround' word.

**Bad news:**
- The above referred benchmark does not work correctly in Preact production build (in development build it works correctly): setState does not trigger component re-render for performance meter.
- Build process for the benchmark never finishes (does not return / exit the process)

**Comment by sventschui** [comment]
The problem is that the minifier will remove the line `const valueExplicitlyUsed = scopedState.value;` (https://github.com/avkonst/hookstate/blob/master/experimental/preact/src/components/LargeTable.tsx#L123) as it is not used. 

Thus this is not a difference between React and preact but rather in the build setup.

Adding a `console.log(valueExplicitlyUsed);` just after that line fixes the issue.

Since a call to `console.log` will negatively impact your benchmark you might want to find a different solution. As I do not know your library it is quite hard to help you in this case. What also works is to adjust the `return <Fragment>` to `return scopedState.value && <Fragment>` - this shouldn't be too bad for performance but you will need to check.

Hope this helps :)

**Comment by avkonst** [comment]
Nice, thanks.
