### ISSUE TITLE
Missed ref

### ISSUE THREAD

**Issue by Crysp** [preactjs/preact#1903]
Preact `forwardRef` missing ref object after re-render

React ✅
https://codesandbox.io/s/react-forwardref-2wxkq

Preact ❌
https://codesandbox.io/s/preact-forwardref-pr1n1

It happens because of
https://github.com/preactjs/preact/blob/a16af189c7194916f540f666d524eb3fcadf9164/compat/src/index.js#L390

Why?

**Comment by JoviDeCroock** [comment]
Hey @Crysp 

No it shouldn't be related to the linked code fragment. The code fragment dictates that we are removing `ref` from the props passed into the vnode. Because we keep our ref on vnode.ref instead, else we would be endlessly passing on ref if we wouldn't remove that from the props. Imagine a scenario where you do this.

```
const App = (props) => {
  return <X {...props} />
}
```

This would effectively make you pass on your ref further down, this feels like a bug with `useImperativeHandle`. I'll look into that tonight. Thanks for the issue report

**Comment by Crysp** [comment]
@JoviDeCroock thx
