### ISSUE TITLE
Preact/Compat - Library

### ISSUE THREAD

**Issue by aguilera51284** [preactjs/preact#1935]
When I updated to preactX, this library failed me :(, whit preact-compat works
https://github.com/yosbelms/react-progressive-loader/issues/10

**Comment by aguilera51284** [comment]
this codesanbox with preact -> 8.5.2 and preact-compat 3.19.0 works
https://codesandbox.io/embed/eager-kepler-irrnr?fontsize=14

and this codesanbox with preact 10.0.0-rc.3 dont work :( 
https://codesandbox.io/embed/preact-x-emotion-ui0j9?fontsize=14

**Comment by yosbelms** [comment]
If any of you are going use `react-progressive-loader` for research of this issue, please use a version before 0.4.1. Because in 0.4.1 `z-index` was added to each `Img` child, which addresses the problem in `react-progressive-loader`, but I think that to find out what made this lib to behave different with different Preact versions worth it to investigate from the Preact POV.

**Comment by JoviDeCroock** [comment]
@yosbelms does the loader use createPortal? Since we are inserting instead of appending I could imagine that being a problem.

**Comment by yosbelms** [comment]
@JoviDeCroock It does not use createPortal it is just plain element composition. If the children reconciliation algorithm changed, it could change the order of children manipulation (not the index in the list)

**Comment by developit** [comment]
@yosbelms was this fixed upstream?
