### ISSUE TITLE
preact@10.0.0-rc.3 svg prop strokeWidth is not equal to stroke-width

### ISSUE THREAD

**Issue by KerryMahne** [preactjs/preact#1940]
For our project we use SVG arcs to render a circular chart.
When upgrading from 8.5.2 to the newest rc, we noticed that our circle charts turned into blobs.
Upon further inspection we realized that the issue occurs on all SVG `path` elements.

After some hair pulling and debugging and checking code differences we came to the conclusion that the newest version doesn't correctly pass the `strokeWidth` property.

When changing it to `stroke-width` it started working properly again.

[Code sandbox example of said behaviour](https://codesandbox.io/s/donout-chart-with-preact-dzx0y).
Check the difference between components Arc and Arc2, they only differ in `strokeWidth` vs `stroke-width`.

**Comment by bojan88** [comment]
@KerryMahne from what I understand Preact is not converting camel case to kebab case. That's being done in `preact/compat` module.

You just need to add this to the top of your script `import { createElement as h } from "preact/compat";`. Here's [updated code sandbox](https://codesandbox.io/s/donout-chart-with-preact-95d8i).

**Comment by KerryMahne** [comment]
Thanks a bunch, we've already did something similar so it works now, I've just wanted to raise awareness of the issue, since we had identical code producing different results in the newest rc.

**Comment by mattly** [comment]
So... `onInput` and `onSubmit` are converted to kebab-case automatically without `preact/compat`... this leads to the impression that any dom element will get its defined props converted automatically. The only thing the docs mention about compat is that it's used for working with ecosystem libraries, not anything about why svg elements get different treatment from html elements.

**Comment by mattly** [comment]
Additionally, the defintion of `strokeWidth` [here](https://github.com/preactjs/preact/blob/master/src/jsx.d.ts#L226) in SVGElements leads me to believe we're supposed to use the camelCased version.

**Comment by marvinhagemeister** [comment]
Sounds related to #2036 .

**Comment by andrewiggins** [comment]
Thanks everyone for the issue and digging in 😁. I took a look myself and below are some of my thoughts:

Re: the original issue (`strokeWidth` not working in `preact`) - `preact` core (not `preact/compat`) does not normalize SVG attributes and properties. SVG is pretty interesting when it comes to the names of its properties and attributes. Some properties (and their attributes) on SVG objects are camelCased (e.g. [`clipPathUnits` on a `clipPath` element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath#Attributes)), some attributes are kebab-case (e.g. [`clip-path` on many SVG elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Presentation)), and other attributes (usu. ones inherited from the DOM, e.g. `oninput` are all lowercase - check out in your browser's console). Normalizing all of these special cases is out of scope for `preact` core as it would be too big for the core renderer :/ .

`preact/compat` however tries to mimic `react` which does normalize these attributes so we have a best effort attempt to get this right. So I think the recommendation, like @bojan88 hinted at, is that if this normalization is important to you and worth the bytes, then use `preact/compat`. Else, use the casing that matches what SVG expects which can be found on MDN (e.g. [path](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path)).

As @mattly pointed out, `preact` core does do some normalization (for legacy reasons) specifically for [DOM events which are typically always all lowercase](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers), which is why `onInput` and `onSubmit` work in `preact` core.

However, it appear our TypeScript typings may be wrong. They do indeed state that `strokeWidth` is supported 😬. We probably need to update some things here and differentiate which properties are allowed in `preact` core and which properties are allowed in `preact/compat`. Perhaps we should open a separate issue for that?

**Comment by marvinhagemeister** [comment]
This issue back from the old `preact-compat` repo may also be of interest: https://github.com/developit/preact-compat/issues/483

**Comment by marvinhagemeister** [comment]
This was fixed with https://github.com/preactjs/preact/pull/2366 . That PR adds the missing SVG normalization to `preact/compat` :tada:
