### ISSUE TITLE
preact@10.0.0-rc.3 preact/compat not compatible with the `informed` library

### ISSUE THREAD

**Issue by shakyShane** [preactjs/preact#1944]
I'm trying to drop `preact/compat` into a large React app (with SSR) - and this is the final blocker for me.

**library in question**:

[informed](https://www.npmjs.com/package/informed)

**description of problem**:

Things such as 'initialValues' just dont work (see the codesandbox), which is the easiest to reproduce, but just in general there seems to be 'internal state problems' with `informed+preact`

**codesandbox** [example of `initialValues` not taking effect](https://codesandbox.io/embed/preact-x-preact-cli-3-starter-uzcn2) 

If you immediately submit that form - you'll see the object logged to the console is missing the initially set value.

---

Many thanks for reviewing :)

**Comment by JoviDeCroock** [comment]
Sorry should've already linked this here:  https://preact.slack.com/archives/C3NMBSJKH/p1569162715058400?thread_ts=1569142082.049000&cid=C3NMBSJKH

I have researched this but gave the response in slack, this code is subject to fail in React concurrent mode due to batching. Preact batches by default.

The clean solution for informed would be to set the initialValues to values at construction instead of relying on two sources of truth.
