### ISSUE TITLE
Cryptic error when using preact/compat

### ISSUE THREAD

**Issue by PepijnSenders** [preactjs/preact#1969]
I just tried to use `preact/compat` on my quite complex project. It was using Preact 8.x before, but when hooks came out we decided to temporarily move back to React. I basically just installed the new preact version and aliased it through `webpack` and then ran my app again. It partially renders and I'm afraid this might have something to do with the partial support for `<Suspense />`, but I'm getting this cryptic error:

```
Uncaught (in promise) TypeError: Cannot read property '__c' of null
    at Object.MOxe.preact__WEBPACK_IMPORTED_MODULE_0__.options.unmount (hooks.module.js:1)
    at D (preact.module.js:1)
    at r (compat.module.js:1)
```

For some reason source mapping also doesn't work for me with `preact/compat` which makes it very hard to debug this by myself.

**Comment by developit** [comment]
Hmm. The stack trace seems to be coming from hooks:
https://github.com/preactjs/preact/blob/4aa291e2af18e53f8106d60a5ab1402d903d5421/hooks/src/index.js#L43

Somehere the unmount hook is getting called with `null` instead of a valid `VNode` object. My guess is that it's [this call to `unmount()`](https://github.com/preactjs/preact/blob/72c370808a080ae99d2bc93b6449dcc2835f7df9/compat/src/suspense.js#L68), which would generate the null case if you're using `<Suspense>` without the `fallback=` prop.

**Comment by jeremy-coleman** [comment]
Mixing imports from preact and preact/compat can cause this , ive found putting preact/compat on window as Preact can help. Webpack bundles are non deterministic so theres no real way to fix it besides forcing 1 bundle. ( the randomness of the ‘optimized’ chunks) . Also , Babel broke things again, because es modules are supposed to be immutable , so in a cjs module u can overwrite the Preact namespace but babel does some jackassery where they break ur app if you do that, i think it was sometime after 7.3.x. Using var instead of const can help also

**Comment by PepijnSenders** [comment]
I was using `<Suspense fallback={null} />` which is valid in `React` and apparently breaks in `Preact X`.

**Comment by PepijnSenders** [comment]
@developit is that something we want to change?

**Comment by marvinhagemeister** [comment]
@PepijnSenders The Suspense API and preliminary support is there in X, but it's not yet recommended for widespread use. It's basically a very early alpha preview and because of that it has many known bugs.

Properly supporting Suspense requires refactoring our renderer architecture a bit, which is doable, but will take time. We didn't ship that with the initial X release, because it would have delayed it way too much.

**Comment by PepijnSenders** [comment]
Understood, it was already quite late so good that you brought it out anyways!

**Comment by developit** [comment]
Supporting a null fallback should be pretty simple. We render Text nodes for null roots.

**Comment by andrewiggins** [comment]
I believe #2030 should fix this issue
