### ISSUE TITLE
Preact undefined in version 10, but not earlier versions

### ISSUE THREAD

**Issue by naheller** [preactjs/preact#2009]
Hello, I am currently using Preact 8 via CDN with the following URL: `https://cdn.jsdelivr.net/npm/preact@8/dist/preact.min.js`

Everything works fine until I change the 8 to 10, at which point the following error shows in the browser console: `Uncaught ReferenceError: preact is not defined`

Here is my `index.html`:
```
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/preact@8/dist/preact.min.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script>
      window.React = { createElement: preact.h }
    </script>
    <script type="text/babel" src="./index.js"></script>
  </body>
</html>
```
And `index.js`:
```
preact.render(<p>Hello World</p>, document.getElementById('root'))
```
The variable `preact` is being referenced in two places: the first script tag of the body section in `index.html`, and the render function in `index.js`. Both throw the error shown above. There are no other files in this app.

Your help is appreciated!

**Comment by developit** [comment]
Hi @naheller - you need to use the UMD version of `preact@10`:

```diff
-<script src="https://cdn.jsdelivr.net/npm/preact@8/dist/preact.min.js"></script>
+<script src="https://cdn.jsdelivr.net/npm/preact@10/dist/preact.umd.js"></script>
```

FWIW I'm hoping we can restore the 8.x "commonjs + globals" behavior to fix this, but if you're loading for web it's safe to always use the UMD version.

**Comment by NicHaley** [comment]
I have a related issue.

I am using `https://cdn.jsdelivr.net/npm/preact@10/dist/preact.umd.js` to get access to the global `preact` inside my application (it's a widget that is loaded by other sites). However, if that site is using RequireJS, because it's UMD format "preact" will not be bound to the window.

This article has a great explanation: https://www.haykranen.nl/2013/05/10/the-problem-with-combining-umd-require-js-modules-and-non-umd-modules/

Is Preact 10+ available in any non-UMD formats?

**Comment by developit** [comment]
There's a PR to add the old behavior of `preact.min.js` here:
https://github.com/preactjs/preact/pull/2261
