### ISSUE TITLE
'clipPathUnits' svg attribute is getting converted to 'clip-pathunits'

### ISSUE THREAD

**Issue by smashercosmo** [preactjs/preact#2036]
Input:
```html
<svg>
  <clipPath id="hexagon" clipPathUnits="objectBoundingBox">
    <polygon points="0.5 0, 1 0.25, 1 0.75, 0.5 1, 0 0.75, 0 0.25" />
  </clipPath>
</svg>
```
output:
```html
<svg>
  <clipPath id="hexagon" clip-pathunits="objectBoundingBox">
    <polygon points="0.5 0, 1 0.25, 1 0.75, 0.5 1, 0 0.75, 0 0.25" />
  </clipPath>
</svg>
```

**Comment by andrewiggins** [comment]
This is cause our [SVG property normalization regex](https://github.com/preactjs/preact/blob/4f130ec2fd5d70a69e2d6313f3710ba19a577823/compat/src/index.js#L38) short circuts on `clip` cuz it thinks the property is `clip-path` which is kebab-case. We need to teach the normalization about `clipPathUnits` which should skip this normalization since that's the [actual property name in this instance](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath#Attributes)

**Comment by developit** [comment]
One other option here would be to investigate allowing SVG props to use properties instead of attributes. In order to do so, we'd have to account for the fact that most SVG properties are `animatedValue` or other odd wrapper types.

**Comment by marvinhagemeister** [comment]
This was fixed with #2251 and it was released as part of 10.3.1 :tada:

**Comment by moklick** [comment]
In the current version there are still issues with incorrect renamings. For example `markerHeight` and `markerWidth` get converted to `marker-height` and `marker-width` which are not valid.

**Comment by marvinhagemeister** [comment]
@moklick Can you file a new issue for that? Comments on closed issues quickly get lost in GitHub's ui, which makes it pretty hard for us to track work.
