### ISSUE TITLE
Render function doesn't return component instance

### ISSUE THREAD

**Issue by sashasashasasha151** [preactjs/preact#2144]
As stated [here](https://preactjs.com/guide/v8/api-reference/#-preact-render-), `Preact.render()` 

> Render a Preact component into the containerNode DOM node. Returns a reference to the rendered DOM node.

But I tried to write it and found that it returns nothing
So, is there a way to get node from render?
I want to get it and then at some time call `remove` on that element

**Comment by JoviDeCroock** [comment]
You are looking at the v8 docs, so to have this behavior you need to use Preact 8. What version are you using?

**Comment by sashasashasasha151** [comment]
> What version are you using?
10.0.0-rc.3

**Comment by JoviDeCroock** [comment]
These are the 10 docs https://preactjs.com/guide/v10/api-reference/#render they show that it doesn't return a value.

**Comment by robertknight** [comment]
The reason `render` doesn't return anything in Preact 10 is that there may be zero, one or many DOM nodes rendered into the container, and there may not be a component instance (at least, not officially) if using a function (rather than class-based) component.

Although you could remove the child nodes using DOM APIs (`container.innerHTML = ''`), this isn't recommended because the component might need to do additional cleanup when it is removed - such as removing subscriptions to external data sources. If you want to remove the rendered content _and run any cleanup processes_, you can render an empty element into the container:

```js
import { h, render } from 'preact';

...

render(h(null), container)
```
