### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by zdroid** [preactjs/preact#2216]
The project has 101 branches in total and at least 60 of them are stale. Something definitely should be done about that.

**Comment by marvinhagemeister** [comment]
We do encourage room for experimentation. I've been able to delete 10 of them, but others are ideas or experiments which may prove useful in the future. I'm not aware of any limits regarding the number of branches here on GitHub.

We have 2 main branches:

- `master` is the current release line.
- `8` is for the previous `8.x` release line.

**Comment by zdroid** [comment]
By having 90 times the same code over, cloning the repository takes almost 90 times more space and time than it could. :wink:

**Comment by JoviDeCroock** [comment]
That's only the case if you'd check out all branches, most of the time you only checkout `master`

**Comment by marvinhagemeister** [comment]
@zdroid please don't make such wild assumptions without checking them against the numbers. I just tried it out locally with two fresh clones. One with a standard clone which downloads all branches and another which just clones the `master` branch. Here are the results:

| Checkout type | Download size |
|---|---|
| All branches | 5.65 MB |
| only `master` |  4.85 MB |

To clone a single branch of a repo git has added the `--single-branch` flag since April 2012. It can be used like this:

```bash
git clone <url> --branch <branch> --single-branch [<folder>]
```
