### ISSUE TITLE
Material-UI 4: popover loose positioning

### ISSUE THREAD

**Issue by rubas** [preactjs/preact#2249]
We are using Gatsbyjs and switched out React with Preact X. Everything works fine, except all the [popover](https://material-ui.com/components/popover/) loose their positioning and open in the top let corner (x: 0, y:0).

```
preact@10.2.1
@material-ui/core@4.8.3
@material-ui/styles@^4.8.2
```

As I haven't found any information, that would suggest, that these wouldn't work with Preact. 

===

Edit: Added an [Example](https://github.com/preactjs/preact/issues/2249#issuecomment-576024118).

**Comment by porfirioribeiro** [comment]
Could you create a small reproduction demo on CodeSandbox?
Would be easier to understand the problem and try to fix it!

**Comment by tky5622** [comment]
I prepare this reproduction instead.
please click TOGGLE MENU GROW and compare normal work.

https://codesandbox.io/s/exciting-worker-i67ug?fontsize=14&hidenavigation=1&theme=dark

https://material-ui.com/components/menus/

**Comment by porfirioribeiro** [comment]
It seems to be working fine, maybe i misunderstood something
 
![Screenshot_20200118_151528](https://user-images.githubusercontent.com/499246/72665964-657a9000-3a05-11ea-86e4-3a10e9c44c9f.png)

**Comment by marvinhagemeister** [comment]
I get the same result as @porfirioribeiro .

**Comment by rubas** [comment]
Thanks. Sorry for the delay, I try to provide an isolated sample later today.

**Comment by rubas** [comment]
Example: https://codesandbox.io/s/relaxed-kepler-gn2sj?fontsize=14&hidenavigation=1&theme=dark

**Bug** Dropdown is opening at `0,0`.


```
import { render, h } from 'preact';
import { PureComponent } from 'preact/compat';
import { FormControl, Select, MenuItem } from "@material-ui/core"

class Foo extends PureComponent {
  render() {
    return (

        <FormControl style={{position: 'absolute',top: 120, left: 120}}>
          <Select value={0}>
            <MenuItem value="0">Test 0</MenuItem>
            <MenuItem value="1">Test 1</MenuItem>
            <MenuItem value="3">Test 3</MenuItem>
          </Select>
        </FormControl>
 
    );
  }
}

const dom = document.getElementById('app');
render(<Foo />, dom);
```

**Comment by antonbashir** [comment]
Same issue with Menu component and anchorEl.
![image](https://user-images.githubusercontent.com/33657862/72858802-0487dc00-3cd3-11ea-8c28-fec6705be6ab.png)
@porfirioribeiro Sorry. Can you please show your example of working code?

**Comment by porfirioribeiro** [comment]
@antonbashir the code that was working was this [codesandbox](https://codesandbox.io/s/exciting-worker-i67ug?fontsize=14&hidenavigation=1&theme=dark) @tky5622 sent: 

Now @rubas [codesandbox](https://codesandbox.io/s/relaxed-kepler-gn2sj?fontsize=14&hidenavigation=1&theme=dark)  i totaly not working

Can you have a look @marvinhagemeister ?

**Comment by tky5622** [comment]
> Same issue with Menu component and anchorEl.
> ![image](https://user-images.githubusercontent.com/33657862/72858802-0487dc00-3cd3-11ea-8c28-fec6705be6ab.png)
> @porfirioribeiro Sorry. Can you please show your example of working code?
 
it seems that the menu can not be displayed Properly unless you get the  button's ref and set it to Menu Component in Preact project.

In the case of react, it still works correctly, but in the case of preact, it is displayed in the upper left instead.

In my sample, it seems to be working because it references the ref correctly.

**Comment by eryon** [comment]
@tky5622 do you have a working example to fetch the button's `ref`?

**Comment by JoviDeCroock** [comment]
I identified the issue, this seems to be a regression in 4.8.2 --> 4.8.3 related to Preact. We'll have to see in what sense we handle the following scenario differently: https://github.com/mui-org/material-ui/pull/19046/files

**Comment by tbgse** [comment]
@JoviDeCroock is there any progress on this already or a recommendation on how to work around it? I'm struggling to make this work at the moment.

**Comment by JoviDeCroock** [comment]
So I haven't had the most time to look into this but from what I can understand this could be due to `findDOMNode` not going outside the `createPortal` similarly to React or  a timing issue, I should have more time the following week to look into this.

What you could do to have a temporary solution is set the anchor like in the one codesandbox where it works or use material ui 4.8.2 instead.

**Comment by tbgse** [comment]
I'm also seeing an error in the console, whenever the popover is opened.
```
Failed ForwardRef(Portal) type: The following props are not supported: `ref`. Please remove them.
```
I wonder if this might be related? 🤔 

Downgrading to 4.8.2 worked well, that should do it for now. Will keep an eye on this thread for updates.

**Comment by tbgse** [comment]
@JoviDeCroock we had to upgrade MUI because of some important fixes that were introduced on their end in the latest updates. Now we're stuck again with the dropdown problem here. I looked into the workaround you mentioned with setting the anchor like in the codesandbox but i believe the only reason why this is working in the sandbox posted here is because it was using an older MUI version before the regression occured (4.8.1).

**Comment by JoviDeCroock** [comment]
Hey @tbgse 

It's extremely hard to debug MUI and there are a lot of patterns used interchangeably, it's quite hard to see what exactly is going wrong.

The error you mentioned above about `ForwardRef` is not a Preact error, this could be indicative of something weird happening, maybe React has some implicit behavior when it comes to Portals, I have no idea atm. I'll look for that error in mui.

**Comment by tbgse** [comment]
@JoviDeCroock this is happening for both popovers ('@material-ui/core/Popover') and select components ('@material-ui/core/Select'). According to their docs the popover is built on top of the modal component (https://material-ui.com/components/popover/) which uses the mui portal api. I'm pretty sure that the select component is also just another layer on top the popover.

**Comment by JoviDeCroock** [comment]
I'll try to dedicate tonight to this issue, might have to see what semantics differ from our `createPortal` implementation that being said it could also just be that the `mountNode` is losing a reference or the semantics of `findDOMNode` being a bit different.

**Comment by tbgse** [comment]
thanks a lot 🙏 , if you need any further info, i'll be around. I prepared a very simple implementation of the dropdown here that highlights the issue: https://codesandbox.io/s/divine-breeze-h8xbi?fontsize=14&hidenavigation=1&theme=dark

**Comment by tbgse** [comment]
@JoviDeCroock any further progress on this?

**Comment by JoviDeCroock** [comment]
I think I’ll have to find a way to test in mui itself since it’s too hard to debug/reproduce on the Preact side. Problem there being that it’s really hard in their build-setup. 

Sorry about this, it’s really hard to debug deep integration issues that revolve around an abundance of moving parts.

**Comment by JoviDeCroock** [comment]
After a fair amount of debugging I found the small discrepancy that is making this fail miserably... The difference between Preact and React is that we'll always resolve children.

This means that for instance in [the following scenario](https://codesandbox.io/s/cranky-field-qu2w0) you see that children is the `Wrapper` functional vnode. If you'd make the same sandbox in Preact this would be `div` since we have resolved it downwards.

Material-ui uses a concept called a `forked ref` when the children are a real dom-node, which for React isn't the case.

Guilty line: https://github.com/mui-org/material-ui/blob/4fba0dafd30f608937efa32883d151ba01fc9681/packages/material-ui/src/Portal/Portal.js#L23

A potential "fix":

```
  const handleEntering = (element, isAppearing) => {
    if (onEntering) {
      onEntering(element, isAppearing);
    }

    if (!paperRef.current) paperRef.current = element;
    setPositioningStyles();
  };
```

On  [this line](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Popover/Popover.js#L332)

This would not solve the whole issue ofcourse but can be temporarily used

**Comment by JoviDeCroock** [comment]
After further investigation the scenario described above isn't the issue, so there are some options worth exploring for me tomorrow relating to `createPortal`.

**Comment by tbgse** [comment]
Thanks for the updates, at first you got me all hopeful, then i read your second message. Fingers crossed you can identify the issue with `createPortal`

**Comment by JoviDeCroock** [comment]
@tbgse glad to tell you I've found a solution

**Comment by tbgse** [comment]
@JoviDeCroock you're a legend! 💪 thanks for all the effort to make this happen.

**Comment by JoviDeCroock** [comment]
This has been released: https://github.com/preactjs/preact/releases/tag/10.3.4

**Comment by tbgse** [comment]
fantastic, works like a charm!

**Comment by JoviDeCroock** [comment]
Glad I could help, wasn't possible without all the help and nice reproductions so a big shoutout to all of you commenting here!
