### ISSUE TITLE
App breaks after root update if rendered with replaceNode

### ISSUE THREAD

**Issue by xkam** [preactjs/preact#2260]
I'm having issue with render replaceNode parameter - the app breaks after I run render the second time with updated properties for the root component. Unfortunately I could not isolate the problem, the simple cases work as intended, so the issue might well be in my code. The first error is indeed in my code, but it looks that it's because something else is broken.

This works fine (1) - https://codepen.io/activewidgets/pen/YzPJebK
```js
render(h(App, initialProps), container);
setTimeout(() => render(h(App, updatedProps), container), 100);
```

This breaks (2) - https://codepen.io/activewidgets/pen/OJPBQKX
```js
render(h(App, initialProps), container, target);
setTimeout(() => render(h(App, updatedProps), container, target), 100);
```

I've found that this one actually works too (3) - https://codepen.io/activewidgets/pen/eYmPVqK
```js
render(h(App, initialProps), container, target);
setTimeout(() => render(h(App, updatedProps), target), 100);
```

Full code (static page) - https://gist.github.com/xkam/098b970d3cbc43427f764491f10dfea1
 
The variant (3) does what I want, so I'm fine if this is an intended use, but from the docs I had the impression that the right one is (2), and that one breaks.

Sorry, the examples have layers of other (less then ideal) code, but I thought that it might be useful anyway.

**Comment by JoviDeCroock** [comment]
I'm sorry I don't know why but codepens always break for me for some reason, so I'm going to do my best to help you out with a previous issue: https://github.com/preactjs/preact/issues/2264

https://codesandbox.io/s/muddy-moon-r9dze

--> This actually uses method 2 so we have to figure out why it goes wrong and I would assume this fails because your dom structure has changed.

Method 3 would use the previously created root from replaceNode so this should work as intended, but method 2 should also work, this might be a bug that we have to trace.

I'm sorry that I can't directly answer your question here, I'll try and run the codepen on my other computer when I get home.

**Comment by zaninime** [comment]
We recently switched some production code from 8 to 10 and had the same unexpected behaviour (we were using method 2). We switched to method 1.-- Francesco Zanini21.01.2020, 14:14, "Jovi De Croock" <notifications@github.com>:I'm sorry I don't know why but codepens always break for me for some reason, so I'm going to do my best to help you out with a previous issue: #2264
https://codesandbox.io/s/muddy-moon-r9dze
--> This actually uses method 2 so we have to figure out why it goes wrong and I would assume this fails because your dom structure has changed.
Method 3 would use the previously created root from replaceNode so this should work as intended, but method 2 should also work, this might be a bug that we have to trace.
I'm sorry that I can't directly answer your question here, I'll try and run the codepen on my other computer when I get home.
