### ISSUE TITLE
Module name node_modules.preact.src.index.d was not provided as a closure compilation source

### ISSUE THREAD

**Issue by capt-obvious** [preactjs/preact#2276]
I'm attempting to compile the preact-cli typescript template (https://github.com/preactjs-templates/typescript); I'm hitting the following roadblock:

```
TSCC: tsickle converts TypeScript modules to Closure modules via CommonJS internally."module" flag is overridden to "commonjs".
TSCC: tsickle uses a custom tslib optimized for closure compiler. importHelpers flag is set.
TS: src/routes/home/index.tsx(5,49): warning TS0: unhandled type {type flags:0x80000 alias:"Readonly" flags:0x80000 TypeAlias aliasArgs:<{type flags:0x200000 IncludesNonWideningType}> Object objectFlags:0x96 object:Mapped object:Instantiated}

TS: src/routes/profile/index.tsx(9,52): warning TS0: unhandled type {type flags:0x80000 alias:"Readonly" flags:0x80000 TypeAlias aliasArgs:<{type flags:0x200000 IncludesNonWideningType}> Object objectFlags:0x96 object:Mapped object:Instantiated}

TSCC: Module name node_modules.preact.src.index.d was not provided as a closure compilation source
TSCC: The compilation has terminated with an error.
```

Any thoughts?

**Comment by developit** [comment]
@capt-obvious can you provide a bit more context here? Preact CLI doesn't use Closure Compiler, so I'm guessing you're trying to process the output of `preact build` using Closure Compiler after the fact?

Otherwise, regarding tsickle - we use TypeScript-style JSDoc annotations in Preact core, but the codebase is not type-checked. There are a number of cases where we do not provide type information (or cannot) due to the fully dynamic nature of the API, or where we have opted to avoid increasing the library size in order to satisfy a typechecker.

You might find #564 interesting. It's from Preact 8, so a somewhat different source shape, but attempts a similar path.
