### ISSUE TITLE
Total js and Preact

### ISSUE THREAD

**Issue by ganga549** [preactjs/preact#2312]
I am a newbie building an app using Preact and Totaljs.
In the form for input fields, to get the value input by the user, totaljs requires value=@{M.email} to be coded in the HTML Input tag element. I am unable to use this in Preact. Preact considers this as the 'value' and my form is prefilled with @{M.email}. Please suggest how to include server side code inside Preact.

**Comment by marvinhagemeister** [comment]
I've read your text a few times but I'm not able to fully grasp what you are trying to do.

If you just want to set the value of an input you can use the `value` property. If you want to be notified of any changes the user makes to the input you need to attach an `onInput` listener (in React that's `onChange`).

I've never heard of total.js but from a quick glance it seems to be about controlling the client from the backend. This fundamentally clashes with the approach in Preact where it's the opposite: Preact controls the client and the backend is just one of the APIs you plug into it. So in short: total.js and Preact are not a good match.

**Comment by developit** [comment]
I'm going to close this out since there's just not enough information to provide a useful recommendation. I looked through the Total.js documentation, and the best I can come up with would be to treat Total.js as an API (over HTTP), and render the client entirely in Preact. Their component definitions are not designed to be used with JavaScript, which is why the HTML-first `value=@{..}` syntax exists. You could theoretically use that to construct a script tag with the server values and pick those up from the client, but at that point the binding syntax is actively harmful and you'd be better off finding a way to dump the server's values into a JSON string.
