### ISSUE TITLE
Support for handleEvent DOM interface

### ISSUE THREAD

**Issue by kurtextrem** [preactjs/preact#2382]
### Reproduction

```jsx
class Foo {
  click(e) {
	this.setState({ clicked: true })
  }

  handleEvent(e) {
    // nicety: `this` is the component
    this[e.type](e)
  }
  render() {
    return <button onClick={this} />
  }
}
```

### Steps to reproduce

Click the button.

### Expected Behavior

handleEvent is used and doesn't throw an error.

### Actual Behavior

`this.l[e.type](P.event ? P.event(e) : e)` throws an error, as `this.l[e.type]` is `this`.

**Comment by marvinhagemeister** [comment]
That's interesting! First time I've hear of it. If you can't wait, you can patch that into Preact via an option hook:

```js
import { options } from "preact";

let oldVNode = options.vnode;
options.vnode = vnode => {
  const { type, props } = vnode;

  // Only check DOM nodes
  if (typeof type === "string") {
    for (const name in props) {
      const value = props[name];
      if (value && typeof value.handleEvent === "function") {
        props[name] = value.handleEvent;
      }
    }
  }
  if (oldVNode) oldVNode(vnode);
};
```

**Comment by kurtextrem** [comment]
Wouldn't it be easier to check if the given event handler is `this` and then call it accordingly? Sadly, I don't understand Preact enough to help fix this - if you tell me how exactly are events added, or where, I could make prepare a PR.

Apart from that, I here is some imaginary code:
"before":
``addEventListener(eventName, preactEventRouter, {opts})``
"after":
``addEventListener(eventName, eventFn === this ? this : preactEventRouter, {opts})``

I hope this shows my point.

(More about this here: https://medium.com/@WebReflection/dom-handleevent-a-cross-platform-standard-since-year-2000-5bf17287fd38)

**Comment by developit** [comment]
The trick here is that we currently use a "proxy" handle in order to avoid constantly removing and re-adding handlers when developers use inline functions in render methods. If we reimplement support for handleEvent on top of function listeners, it loses all of the performance advantages. 

**But**! I think there might be a way for us to switch to internally using handleEvent...

**Comment by kurtextrem** [comment]
Sounds reasonable and the **but** sounds interesting. Any help needed in exploring?

**Comment by developit** [comment]
Definitely! I can throw a PR together that should at least show the rough outline of what we are proposing here, then we can go from there?

**Comment by kurtextrem** [comment]
Sure, let's do this :)

**Comment by developit** [comment]
Just an update since I stumbled on this in my neverending list of tasks: I did get a chance to prototype full support for object event listener values in Preact, it just ends up being a size increase we'll need to find workarounds for:

https://gist.github.com/developit/bd824b90cd4c26db0d99576bd4737273

**Comment by lilnasy** [comment]
Bringing this back from the dead because I want this feature as well and I'm willing to open a PR if the design makes sense.

I read through developit's gist and I think it will have an unintended side effect: if even the normal function listeners are being converted into the `EventListenerObject` interface, they will now receive something as `this` whereas it was `undefined` before. It might not be breaking, but I suspect it will be confusing during development at best.

Additionally, since the original object is being copied before being added as a listener, the method will lose access to `#private` fields. Then again, I might be reading into too much into that specific version of the gist - it may not be an important aspect.

I propose that listeners be allowed more diversity, and that the event proxy check whether the listener implements `handleEvent()` to call it differently. We would be emulating the browser's behavior manually.

As for contribution to the package size, I expect it to not be much more than the addition of a `"handleEvent" in eventHandler` check right around here:
https://github.com/preactjs/preact/blob/b7c43d9b52f2809ab43ee34aea829ecffd935f89/src/diff/props.js#L169

**Comment by rschristian** [comment]
Certainly feel free to open a PR, we can take a better look at perf & size there when/if you do.
