### ISSUE TITLE
Warn on invalid HTML hierarchy

### ISSUE THREAD

**Issue by jennydaman** [preactjs/preact#2399]
# Example

https://github.com/jennydaman/preact-p-problem/blob/707dc6fd35c5422e610202ee7d40a2c3706a6b3e/src/index.js#L10-L18

Elements inside a JavaScript list which are rendered as children of a `<p>` have their HTML attributes dropped and put onto other elements of the same tag found below.

This bug only affects `<p>`, does not happen to `<div>`, `<span>`, `<b>`, nor `<section>`.

# Result

![colors are in wrong place](https://user-images.githubusercontent.com/20404439/76154906-34881480-60b2-11ea-8d5a-5942b1ca4800.png)

# Expected

preact-cli actually pre-renders it correctly. We can get the correct result by disabling JavaScript in the browser.

![expected result with javascript disabled](https://user-images.githubusercontent.com/20404439/76154946-1a9b0180-60b3-11ea-870c-b858a4b44d73.png)

**Comment by marvinhagemeister** [comment]
That's very interesting! Thanks a bunch for reporting this issue and the excellent reproduction case :tada: 

Had a quick look at it and it seems that the issue only occurs in production builds. In dev mode everything looks to be correct, making these even more strange. Will need to look further...

**Comment by marvinhagemeister** [comment]
Ok so we're in hydration mode and somehow the rendered html in `index.html` is completely wrong:

```html
<div>
  <p id="problem"></p>
  <div style="color: red">a</div>
  <p style="color: blue">b</p>
  <div style="color: green">c</div>
  <p></p>
  <i>Spring</i>
  <div>break</div>
  <div>is</div>
</div>
```

**Comment by marvinhagemeister** [comment]
Alright, I got it :tada: Initially I assumed that there must be a problem in `preact-render-to-string` but that's not the case. It renders the correct result.

Instead the weird behaviour is actually written down in the [HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element) itself. It states:

> Tag omission in text/html:
>
> A `p` element's end tag can be **omitted** if the `p` element is immediately followed by an `address`, `article`, `aside`, `blockquote`, `details`, `div`, `dl`, `fieldset`, `figcaption`, `figure`, `footer`, `form`, `h1`, `h2`, `h3`, `h4`, `h5`, `h6`, `header`, `hgroup`, `hr`, `main`, `menu`, `nav`, `ol`, `p`, `pre`, `section`, `table`, or `ul` element, or if there is no more content in the parent element and the parent element is an HTML element that is not an `a`, `audio`, `del`, `ins`, `map`, `noscript`, or `video` element, or an autonomous custom element.

So this means that this:

```html
<p id="problem">
  <div style="color: red">a</div>
  <p style="color: blue">b</p>
  <div style="color: green">c</div>
</p>
```

will be turned into:

```html
<p id="problem"></p>
<div style="color: red">a</div>
<p style="color: blue">b</p>
<div style="color: green">c</div>
<p></p>
```

At this point the DOM hierarchy has changed substantially and the `<p>`-tag doesn't wrap the colored children anymore.

What's worse is that the DOM hierarchy you're trying to render is invalid and browsers immediately enter the "quirks"-mode, where the browser tries to guess what the developer tried to achieve with the html document. This differs from browser to browser and is somewhat undefined behaviour. It's safe to say that the outcome is rarely what's expected.

The reason the HTML is invalid is because a `p`-tag does only allow phrasing content as children, which is defined here: https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2 Putting a `div` tag as a child of `p` is therefore invalid. Same as nesting `p` tag. That's invalid, too.

Following the guidelines of the spec we can use `span` elements as children:

```jsx
export default class App extends Component {
  render() {
    return (
      <div>
        <p id="problem">
          {[
            <span style="color: red">a</span>,
            <span style="color: blue">b</span>,
            <span style="color: green">c</span>
           ]}
        </p>
        <i>Spring</i>
        <div>break</div>
        <div>is</div>
      </div>
    );
  }
}
```

I'm wondering if there is a way for us to warn the user in `preact/debug`.

**Comment by jennydaman** [comment]
Interesting find, thank you for digging into it.

I had a hunch that it had to do with an oddity in the HTML spec, however I was unaware that I was misusing `<p>`. It is strange because this means the tag type of the parent actually matters.

**Comment by just-boris** [comment]
In case if this helps, here is how React checks the proper DOM nodes nesting: https://github.com/facebook/react/blob/0cf22a56a18790ef34c71bef14f64695c0498619/packages/react-dom/src/client/validateDOMNesting.js

**Comment by developit** [comment]
Definitely can't go the spec validation route here, so our options are basically limited to bailing out of non-corrective hydration when encountering tree mismatch. I have a WIP version of this locally I'll try to extract from my progressive hydration stuff.

**Comment by marvinhagemeister** [comment]
@arty-name This is not an issue in Preact, but of an invalid HTML hierarchy that the user told Preact to render. A `div` **must** not be inside a `p` element per spec.

We've left this issue open because we would like to print a red warning sometime in the future via `preact/debug`.

**Comment by arty-name** [comment]
Thank you for explaining Marvin! I also figured it out, but the warning is not printed yet, so I thought this minimal case might be useful. Maybe I just didn't want to throw it away :)

**Comment by marvinhagemeister** [comment]
Awesome, thanks for the sandbox! We'll check it out 👍

**Comment by rschristian** [comment]
As of #4108 / v10.18.0, we are printing errors to the console for a few common invalid nesting situations.
