### ISSUE TITLE
Difficult to debug error "Objects are not valid as child"

### ISSUE THREAD

**Issue by nojvek** [preactjs/preact#2415]
Currently importing/requiring preact will load `preact.module.js` which is a minified version of preact. 

![image](https://user-images.githubusercontent.com/1018196/76659943-fae15e80-6534-11ea-8e46-d9bd4d745468.png)

Its nice and small but a PITA to debug preact issues. Right now preact is throwing unuseful errors like 

![image](https://user-images.githubusercontent.com/1018196/76659985-164c6980-6535-11ea-9298-3ce71f3e5655.png)

I have no idea where the problem is occuring, what is the object? Debugging the minified preact bundle is not very helpful. Preact totally borks the UI after this error fires.  Elements dissappear, layout breaks, clicking on buttons don't work. No other errors, just that error. Until user refreshes the app, there is no way to recover. Preact really breaks.

Is there a way to get a dev bundle so I can figure out what is going wrong. I took a risk going with preact since its smaller, but weird issues like this make me wonder "may be should have gone with react which has a much bigger community"

**Comment by nojvek** [comment]
mmmm okay so doing `import {h, render, Component, Fragment} from 'preact/src';` gives the dev version but the error doesn't happen in dev version, only when `preact` is imported directly. Makes me thing this is some sort of minifier bug. Or preact has different behavior between dev and prod versions.

**Comment by marvinhagemeister** [comment]
The warning originates from `preact/debug`. When you change you're import from `preact` to `preact/src` you'll essentially end up with 2 copies of Preact in your bundle since `preact/debug` references the prod one. That's why no warnings will be shown anymore.

I've made a PR #2416 which adds a component stack to the error message. Somehow we missed this error when we added those.

Example:

![Screenshot from 2020-03-14 07-08-10](https://user-images.githubusercontent.com/1062408/76676418-8b668000-65c3-11ea-846e-a9a000f23959.png)

**Comment by faelpinho** [comment]
Just for note: In my case, I had this error because I tried to render a Javascript object directly that can't be interpreted as valid JSX content (render a prop typed as Date). I fix it using .toString().

Example:
```Javascript
const allEntries = [ { Name: "value1", InsertionDate: new Date() } ];

allEntries.map(data => {
    return <p>{data.Name} at {data.InsertionDate.toString()}</p>
})
```
