### ISSUE TITLE
Issue with forwardRef and grommet 2.11.2

### ISSUE THREAD

**Issue by eclipticccc** [preactjs/preact#2484]
When including a Grommet component (that requires AccordionPanel) using Preact 10.4.0, it throws an error because `withForwardRef` attempts to set the name of a function.

It seems that Preact returns a function from `forwardRef`, whereas React returns an object.

Error thrown:
```
TypeError: Cannot assign to read only property 'name' of function 'function t(t) {
    var e = E({}, t);
    return delete e.ref, n(e, t.ref);
  }'

/node_modules/grommet/es6/components/hocs.js:186
  183 |   }, props));
  184 | });
  185 | ForwardRefComponent.displayName = getDisplayName(WrappedComponent);
  186 | ForwardRefComponent.name = ForwardRefComponent.displayName;
  187 | ForwardRefComponent.defaultProps = WrappedComponent.defaultProps;
  188 | hoistNonReactStatics(ForwardRefComponent, WrappedComponent);
  189 | return ForwardRefComponent;
```

**Comment by marvinhagemeister** [comment]
That's really weird that they're setting both `displayName` and `name`. The reason `displayName` came to be is exactly the issue you're describing. To me it sounds like something that should be fixed in `grommet`.

There is no reason why one would want to set `name` and the whole ecosystem has settled on `displayName`. See this section in the React docs: https://reactjs.org/docs/react-component.html#displayname
