### ISSUE TITLE
Legacy Context values are not updated on change

### ISSUE THREAD

**Issue by pl12133** [preactjs/preact#2498]
Using `preact@10.4.0` and `preact-context-provider@preactx`, changing a value passed to the `Provider` does not cause that value to be updated in context.

### Reproduction

JSFiddle: https://jsfiddle.net/kd4we9nj/

### Steps to reproduce

1. Render `<Provider value={'value one'}>`, observe value in context of child component equals `context.value === 'value one'`.
2. Render `<Provider value={'value TWO'}>`, observe value in context of child component still equals `context.value === 'value one'`.

### Expected Behavior

Upon changing the props passed to `Provider` after its initial render, those changed values should be reflected in component context.

### Actual Behavior

The value in context is always set to the value passed to `Provider` on its initial render. Changing the props passed to `Provider` do not cause the value of context to change.

### Workaround

Add a `key` prop to the `Provider` which changes any time the context value should be updated.
____

I don't think this is caused by anything in `preact-context-provider`, since it is implementing a very simple `getChildContext` method which has worked in the past.

Original issue from `preact-i18n`: https://github.com/synacor/preact-i18n/issues/39

**Comment by MykalMachon** [comment]
I think I've also been running into this issue. 
I've been trying to share some state across components using context but consumers don't seem to update when the provider is re-rendered. 

@pl12133 Have you found another solution for this past providing a key prop to the provider? 

Thanks in advance.

**Comment by marvinhagemeister** [comment]
Narrowed it down to this line: https://github.com/preactjs/preact/blob/2744ac4a8b02f3d394736a1dac00e3db409f608d/src/diff/index.js#L130

We could fix it by adding a check for context equality, but this has very wide reaching implications.

```js
if (... ||
  (newVNode._original === oldVNode._original &&
  c.context === componentContext)
) {
  ...
}
```

I'm not comfortable with making that change as it would make it impossible to bail out of a render via `useMemo` or when we return exactly the same `vnode`. The legacy `getChildContext`-API has various problems with keeping subscribers up to date by design, like not being able to pass through `shouldComponentUpdate`. I'm really curious if it would be easier to just go with `createContext` instead which addresses all of those missing update problems.

Converting the part of [preact-context-provider](https://github.com/synacor/preact-context-provider/) that's used in the fiddle to the modern context API boils down to these 9 lines: 

```jsx
export const Ctx = createContext({});
export function PreactContextProvider2(props) {
	const value = {};
	for (const k in props) {
		if (k !== 'key' && k !== 'children') {
			value[k] = props[k];
		}
	}
	return <Ctx.Provider value={value}>{props.children}</Ctx.Provider>;
}
```

With that we can pull the context value via a hook in `RenderValueFromContext`:

```jsx
import { useContext } from "preact/hooks";

function RenderValueFromContext() {
	const { value } = useContext(Ctx);
	return <div>{value || 'Value from context is not set'}</div>;
}
```

...and we see that everything works as expected:

```txt
Context Initialized
```

If one doesn't want to use hooks, one can use the following (admittedly weird) React API. Note that it only works with class components.

```jsx
class RenderValueFromContext extends Component {
	static contextType = Ctx;
	render() {
		const { value } = this.context;
		return <div>{value || 'Value from context is not set'}</div>;
	}
}
```

**Comment by marvinhagemeister** [comment]
Took it up with the team and we've come to the conclusion that the `createContext`-API should be used here. It's the only context API that guarantees that all subscribers will be notified of updates.

**Comment by pl12133** [comment]
Thanks @marvinhagemeister, for `preact-i18n` we will definitely get rid of `getChildContext` and then we will have to decide if `preact-context-provider` is necessary anymore or it should be deprecated along with legacy context.

**Comment by marvinhagemeister** [comment]
@pl12133 FYI: `preact-context-provider` is only needed for Preact 8.x. For Preact X and onwards you can import it directly:

```js
import { createContext } from "preact";
```
