### ISSUE TITLE
Blank page on build for v10

### ISSUE THREAD

**Issue by snguyenthanh** [preactjs/preact#2513]
### Reproduction

Migrating from [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate), on `npm run build`, the page is blank and there are no errors on the console. Although it works well on `development`.

![image](https://user-images.githubusercontent.com/35214933/80857146-610b7780-8c82-11ea-98c5-93964ccd7f4e.png)

My configuration files:
- [babel.config.js](https://gist.github.com/snguyenthanh/811a2a3e7c271ad33b901dc638c5d489)
- [package.json](https://gist.github.com/snguyenthanh/9121a468b0dc2a0c6250c5e17c38ea5b)
- [webpack.base.babel.js](https://gist.github.com/snguyenthanh/fcaf872a311395ce2b81ee0931826f6e)
- [webpack.dev.babel.js](https://gist.github.com/snguyenthanh/5cef5ad9854cb9de27c165a13daa4a5a)
- [webpack.prod.babel.js](https://gist.github.com/snguyenthanh/f3238109bdc78fdc82431cb260848db9)

Am I missing anything in the configurations ?
Otherwise, are there any methods to debug preact in `production` build ?

### Steps to reproduce

Using the above configurations for `react-boilerplate`, and only add `alias` (as mentioned in [Getting Started](https://preactjs.com/guide/v10/getting-started/#aliasing-react-to-preact)) in `webpack.base.babel.js`.

**Comment by marvinhagemeister** [comment]
With the configuration files alone I wasn't able to get something quickly running without having to spent an hour getting everything set up. So I did the following instead to reproduce the error you described:

1. Clone [react-app-boilerplate](https://github.com/react-boilerplate/react-boilerplate)
2. `npm install preact`
3. Add Preact alias to `webpack.base.config`
4. Run `npm run start:production`

With a working reproduction case I was able to narrow it down to a faulty babel plugin: `@babel/plugin-transform-react-inline-elements`.

Removing `@babel/plugin-transform-react-inline-elements` in `babel.config.js` fixes the issue.

## Explanation

This plugin was commonly used during the React 0.14 era as an optimization. It replaces `React.createElement` calls with a function injected by the plugin. This was in 2015 when React's `createElement` function was a bit slow.

Since this time a lot of advancements have been made making this optimization unnecessary, even harmful as it is slower than just calling `React.createElement` directly. This true even for current versions of React.

That's also the reason why it isn't enabled in `create-react-app` at all.

**Comment by snguyenthanh** [comment]
@marvinhagemeister It works now! Thank you so much for your time and effort. The explanation was clear as well :)
