### ISSUE TITLE
Circular references resulting from h

### ISSUE THREAD

**Issue by edemaine** [preactjs/preact#2515]
### Reproduction

```js
require('preact').h('img')
```

results in

```
{
  type: 'img',
  props: {},
  key: undefined,
  ref: undefined,
  __k: null,
  __: null,
  __b: 0,
  __e: null,
  __d: undefined,
  __c: null,
  constructor: undefined,
  __v: [Circular]
}
```

This structure has a circular pointer (I guess made by `createVNode` in [this line](https://github.com/preactjs/preact/blob/master/src/create-element.js#L82)), which makes it not JSON serializable.

This used to work fine on Preact 10.1.1, but has a circular dependency in Preact 10.4.1.

### Expected Behavior

It would be really nice if VNodes were JSON serializable.  I use it in [this project](https://github.com/edemaine/svgtiler/) to detect equality among many different data types (strings, VNodes, etc.).

I imagine this circular reference could also lead to memory leaks...

**Comment by developit** [comment]
Just a note: Preact's VNodes are technically not JSON-serializable, since they're required to have an undefined `constructor` value. That being said, it sounds like you've got a case where that's not applicable - you're only serializing for the purposes of comparison and aren't then deserializing.

There's an ongoing discussion of what to do about `_original` / `__v`. It provides some important performance optimizations, though it may be possible for us to achieve those without using an full self-reference.

**Comment by edemaine** [comment]
@developit Thanks for the heads up! I'm not sure what performance optimization that enables, but I'm not very familiar with Preact's codebase. Without knowing the motivation, circular references seem like they ought to be avoided... at least when just calling `h`. (In my context, all I'm doing is using `preact-render-to-string` to render directly to HTML, or in my case SVG, and not using an actual living VDOM.)

But assuming circular references really are optimal: I guess it's not really crucial that I can serialize; in my setting, I could use `preact-render-to-string` and compare those strings. Perhaps there should be some official API for destroying a VNode, though, to enable garbage collection?

**Comment by developit** [comment]
All current JS engines (including the last few IE versions) use mark-and-sweep GC, which handles circular references without leaks ([more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#Cycles_are_no_longer_a_problem)).

Some context on the optimization: Preact's job on the client is to compare trees of objects to see what changed. In order to prevent shared mutation problems, it often has to clone those objects before using them ([example](https://github.com/preactjs/preact/blob/b9d457f9fc54881de4dfbc86287cd3487d468597/src/diff/children.js#L68-L94)). When we clone a VNode, we set its `.__original` property to the "source" VNode (for non-cloned vnodes, the source is itself). This lets us check whether the original VNodes are referentially-equal when comparing clones ([example](https://github.com/preactjs/preact/blob/b9d457f9fc54881de4dfbc86287cd3487d468597/src/diff/index.js#L130) [example](https://github.com/preactjs/preact/blob/b9d457f9fc54881de4dfbc86287cd3487d468597/src/diff/index.js#L211-L216)).

In terms of a path forward, there is some work afoot that removes the need for `.__original` entirely, which is the move to a single long-lived "backing tree". Once that's landed, Preact VNodes will be pure `{ type, props, constructor: undefined }` objects.

---

Now, back to your comparison use-case, you should be able to just use `type` and `props`:

```js
import { toChildArray } from 'preact';

function serialize(vnode) {
  if (!vnode || typeof vnode !== 'object') return vnode;
  const props = Object.assign({}, vnode.props);
  props.children = toChildArray(vnode.props.children).map(serialize);
  return {
    type: vnode.type,
    props: vnode.props,
    key: vnode.key,
    ref: vnode.ref
  };
}
```

The other option though, as you mentioned, would be `preact-render-to-string`. We actually have a variant dedicated specifically to your use-case (comparison and visualization):

```js
import renderToString from 'preact-render-to-string/jsx';

const img = h('img');
renderToString(img);
// <img />

const Foo = () => {}, Bar = () => {};
const complex = h(Foo, { title: h(Bar) }, 'hello');
renderToString(complex, { shallow: true });
// <Foo title={<Bar />}>
//   hello
// </Foo>
```

There are some decent options for controlling how serialization works (attributes, whether to use self-closing tags, whitespace, etc) [here](https://github.com/preactjs/preact-render-to-string/blob/18332cb804e8e15ae852b4cdff53c862a777f7be/src/jsx.js#L53-L61).

**Comment by edemaine** [comment]
Thanks for the further explanation why this is useful.  I didn't realize everyone already does proper garbage collection -- glad that's not an issue!  (Clearly I've done too much Python programming.)

Your `serialize` preprocessor would work in my case, except in my case, I'm comparing a user-specified value that *could* be a VNode, or it could be a string or an `xmldom` object, so I need to separate the cases.  Is there a standard way to check whether an object is a VNode?  I'm currently using `typeof data === 'object' and data.type != null and data.props != null`, as I didn't see API for this, but maybe I missed it.

I am looking forward to when "Preact VNodes will be pure `{ type, props, constructor: undefined }` objects." because my project doesn't use the Preact `render` function at all, only the `h` builder followed by eventual `preact-render-to-string`, so that'll be more efficient overall for me.  But I can make do meanwhile. 🙂 

P.S. I just started a new project that uses Preact's `render`, and it's quite fun to see it all working as normally intended. 🙂
