### ISSUE TITLE
Aliasing preact/compat for SSR

### ISSUE THREAD

**Issue by zsolt-dev** [preactjs/preact#2554]
Hi,

I have just spent two ours on aliasing preact/compat. And I though switching to preact will be easy :)

So after two hours I learned that:
1. if I want to have SSR, I need two aliases.
- one in webpack as documented
- one for SSR via module-alias/register

The module-alias/register will not work with webpack, so you have to have two aliases.

This will still not fix the problems in VS code 
```
Unable to resolve path to module 'react'. (eslint import/no-unresolved)
```

2. One would think that the elegant solution is to do aliasing via NPM directly, as documented here:
https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md

But since npm aliases cannot alias to specific package directory, this does not seem to work.

I think that the only correct way is to alias is via NPM alias, but that does not work unless there is a standalone package for compat (like it was before).

**Comment by developit** [comment]
There is a standalone package for preact/compat: `@preact/compat`
https://www.npmjs.com/package/@preact/compat

npm aliases do work well for VSCode and your app, but they _do not always work_ for dependencies. Say you import an npm dependency like `react-router`, that dependency may include `"dependencies":{"react":"^16"}` and it will install and use React rather than Preact.

For this reason, I strongly recommend using _both_ npm aliases _and_ `module-alias` or webpack. You can do this with a single configuration:

**package.json**:

```json
{
  "dependencies": {
    "preact": "^10.4.4",
    "react": "npm:@preact/compat@^0.0.2",
    "react-dom": "npm:@preact/compat@^0.0.2"
  },
  "_moduleAliases": {
    "react": "node_modules/react",
    "react-dom": "node_modules/react-dom"
  }
}
```

**webpack.config.js**:

```js
module.exports = {
  resolve: {
    alias: require('./package.json')._moduleAliases
  }
}
```

**ssr.js**: (or whatever you're using for SSR)

```js
require('module-alias/register');
```

**Comment by zsolt-dev** [comment]
@developit thank you for your response and pointing out the standalone package.

Just leaving some more info for the next person that will have the same issue.

This did not work for me, since webpack aliases need package names instead of paths to packages in node_modules dir:
```
module.exports = {
  resolve: {
    alias: require('./package.json')._moduleAliases
  }
}
```

And when I switched package.json to this:
```
  "_moduleAliases": {
        "react": "preact/compat",
        "react-dom": "preact/compat",
  }
```
it did not work for SSR which needs file path instead of package names.

So I ended up having to keep the webpack alias hardcoded like this:
```
      alias: {
        react: 'preact/compat',
        'react-dom': 'preact/compat',
      },
```
