### ISSUE TITLE
preact.hydrate doesn't update element attributes

### ISSUE THREAD

**Issue by w4zZz4p** [preactjs/preact#2572]
### Reproduction
Code for reproduction is located here: https://github.com/gecharo/preact-hydrate-test

### Steps to reproduce

```
yarn
node index
navigate to http://localhost:3000/
```

view source

### Expected Behavior

`class` attribute should be equal to `"client"`
`id` attribute should be equal to `"id_client"`

### Actual Behavior

`class` attribute is equal to `"server"`
`id` attribute is equal to `"id_server"`

In short, when using `hydrate` element attributes aren't updated, though content is!

It seems that this behavior occurred after preact version 10.3.3, before it was ok.

**Comment by JoviDeCroock** [comment]
This is expected, `hydrate` should not diff properties.

**Comment by marvinhagemeister** [comment]
Like @JoviDeCroock said, this is by design. The whole point of hydration is to display interactive content as quickly as possible to the user by re-using the existing HTML. The fastest way to do that is to skip the diffing as much as possible and only attach event handlers. That's what `hydrate()` does.

In your case it looks like you don't want to hydrate your HTML, but want to do a full diff pass instead. That's what `render()` is for.

**Comment by w4zZz4p** [comment]
Thanks for clarification
