### ISSUE TITLE
createContext Update Flag

### ISSUE THREAD

**Issue by Myrdden** [preactjs/preact#2606]
So, `React.createContext` has a barely, if at all documented feature, in that it takes a second argument, which is a function that returns a binary, which somehow can be used by Consumers to determine whether they need to update. I'm not super clear on the specifics of how it works, because I don't actually use it for it's intended purpose. Instead, by passing `() => 0b0`, I can can create a context that never triggers a render when the value updates, and for whatever reason this doesn't render the Provider itself, but consumers still see the updated value when they render by other means.

This seems a bit niche, but I've found this pattern cropping up time and time again in the boilerplate of my application, because it's a really convenient way to pass callbacks and utilities around in a sort of plug-and-play manner without a bunch of prop drilling. Having this feature in Preact would be great.

(Or, if someone wants to point out that this is a ridiculous strategy that can be accomplished via more mainstream means, that would also be welcome.)

**Comment by marvinhagemeister** [comment]
It's undocumented for a reason as it's a pretty weird API and an experiment that didn't lead to the results initially everyone hoped for. The experiment was done at a time when `react-redux` was trying to leverage the new context API for fine granular updates. The trouble is that those semantics are specific to the library in use and there are many competing ways to to those, which all have their different strengths and tradeoffs. Forcing state management to chose a particular tradeoff by (P)React is wrong.

> I'm not super clear on the specifics of how it works, because I don't actually use it for it's intended purpose. Instead, by passing () => 0b0, I can can create a context that never triggers a render when the value updates, and for whatever reason this doesn't render the Provider itself, but consumers still see the updated value when they render by other means.

It mainly works by setting a bitmask and using that to mark properties as new. You can get the same behaviour of not updating the provider by mutating the value passed to the `Provider` instead of passing a new value on each render.

**Comment by Myrdden** [comment]
@marvinhagemeister 
> It mainly works by setting a bitmask and using that to mark properties as new. You can get the same behaviour of not updating the provider by mutating the value passed to the `Provider` instead of passing a new value on each render.

Not sure what you mean by this. If it's not too much trouble, could you provide an example?

**Comment by ForsakenHarmony** [comment]
very simplified:

```js
// possibly in a `useRef`
let val = { callback: () => {} };

<Provider value={val}>...</Provider>

// then later
val.callback = function cb() { ... }
```
