### ISSUE TITLE
useRef breaks and triggers the "Object doesn't support this action" error in IE11

### ISSUE THREAD

**Issue by iKonrad** [preactjs/preact#2667]
Using `useRef` with null value will trigger an `Object doesn't support this action` in IE11.

#2458 # Reproduction

Preact version: 10.4.6

### Steps to reproduce

1. Import useRef with `import { useRef } from 'preact/compat';`
2. Create a ref with `const element = useRef(null);`
3. Pass it on to the element: `<input ref={element} />`;
4. Open the app in IE11.
5. Notice error in the console

### Expected Behavior

No error in the console and refs working corectly

### Actual Behavior

![image](https://user-images.githubusercontent.com/3729309/88913784-e7bff880-d261-11ea-8da5-d6e798566746.png)

**Comment by JoviDeCroock** [comment]
I've tried running 

```
import { useRef } from 'preact/hooks';

...
```

Which doesn't result in the error, this means that your version of IE11/Windows, I assume IE11 on Windows 7 has this issue. Since our SauceLabs doesn't result in an error when testing IE11 on Windows 10. This version of IE11 seems to have an issue with one of our calls to `Object` inside of `/compat`

**Comment by marvinhagemeister** [comment]
Just checked on IE11 on Windows 17 via BrowserStack and I can't reproduce the described issue anymore 🎉
