### ISSUE TITLE
preact is based on prototype now,  why not be based on class ?

### ISSUE THREAD

**Issue by anlexN** [preactjs/preact#2670]

**Comment by developit** [comment]
The size is significantly smaller due to transpiler overhead. Since there is no standard for how to publish modern code to npm, we are forced to publish only ES5 source. This means we optimize for ES5. 

When there is widespread support for not only publishing but consuming and deploying modern npm libraries, we can consider moving to class. For now it would result in preact's size being effectively a meaningless vanity statistic.

**Comment by anlexN** [comment]
what time?

**Comment by marvinhagemeister** [comment]
@anlexN There is no known timeline when the whole JavaScript ecosystem is ready for that. There have been a few proposals in the past few months on how more modern syntax versions can be consumed from npm without breaking every bundler (webpack, rollup, parcel,...), but there hasn't been a clear winner yet. What's more is that the maintainers of the various bundlers have different opinions on which way to move forward.
