### ISSUE TITLE
Preact/compat - Input value does not show up in the HTML

### ISSUE THREAD

**Issue by christianpv** [preactjs/preact#2675]
### Reproduction

* Preact https://codesandbox.io/s/kind-leakey-d99eb?file=/src/App.js
* React https://codesandbox.io/s/nervous-microservice-f3dbh?file=/src/App.js

### Steps to reproduce

Type "anything" in the email input.

### Expected Behavior

Inspecting the input element shows a value of "anything".

### Actual Behavior

Inspecting the input element does not show a value.

### Note

If the default value is an empty string, the input value appears as an empty string in React.
<img width="829" alt="Screen Shot 2020-08-03 at 8 31 24 PM" src="https://user-images.githubusercontent.com/6967580/89239833-5980a500-d5c8-11ea-8987-88cef7a03213.png">

**Comment by sventschui** [comment]
Thank you for reporting this issue. This seems to be (kinda) expected behaviour as we are using different DOM APIs as react does and thus the browser devtools are not updated.

Would you mind sharing your usecase where this is an issue? 

Note that this only affects `getAttribute('value')` but not `.value`:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/512692/89291873-9649ac00-d65b-11ea-8ff2-a1e5e57b5090.png">

<img width="495" alt="image" src="https://user-images.githubusercontent.com/512692/89291896-9fd31400-d65b-11ea-945a-55842491b728.png">

**Comment by developit** [comment]
This is working as intended. Value should never be reflected in the DOM, doing so is a (severe) security vulnerability. IIRC this behavior is being corrected in a future version of React.

FWIW, Preact does correctly render using the `value=""` attribute during SSR, when it's actually necessary and intended.

**Comment by christianpv** [comment]
@developit Thanks for the quick reply. I ran into this issue when I tried to replace React with Preact. Some of our unit tests were not passing due to the value not rendering but this issue is not affecting us anymore since we rewrote the tests. Thanks again!

**Comment by developit** [comment]
Awesome - thanks for the context, that's useful to know. It might be good for us to update the docs to cover this somehow.
