### ISSUE TITLE
Preact/compat - StrictMode should call shouldComponentUpdate twice in DEV

### ISSUE THREAD

**Issue by christianpv** [preactjs/preact#2676]
### Reproduction

* Preact https://codesandbox.io/s/kind-leakey-d99eb?file=/src/App.js
* React https://codesandbox.io/s/nervous-microservice-f3dbh?file=/src/App.js

### Steps to reproduce

Type "a" in the email input.

### Expected Behavior

Console log shows the value "a" twice.

### Actual Behavior

Console log shows the value "a" once.

### Note

React added this change in the following PR: https://github.com/facebook/react/pull/17942

**Comment by sventschui** [comment]
Thank you for the bug report.

The "problem" here is that we do not have a "DEV Mode" as react has. We might want to add this to `preact/debug` though since I understand this "feature" more as a hint for developers to not rely on side effects in sCU as it might be called multiple times in the future (concurrent mode).

**Comment by developit** [comment]
Since we don't have a dev mode, we won't be adding this feature. It's not an API decision, it's a forcing function the react team is using to make sure developers don't rely on lifecycle timing semantics. Preact is not changing those timing semantics, so we have no reason to intentionally break them as a developent aide. No code should ever be relying on sCU being called twice, doing so would be a hack.
