### ISSUE TITLE
Preact/compat - Input maxLength of null should be equal to undefined

### ISSUE THREAD

**Issue by christianpv** [preactjs/preact#2677]
### Reproduction

* Preact https://codesandbox.io/s/great-mcclintock-0wq7x?file=/src/App.js
* React https://codesandbox.io/s/blue-wind-bp071?file=/src/App.js

### Steps to reproduce

Type "anything" in the email input.

### Expected Behavior

Can type "anything" since maxLength is not enforced. Inspecting the input element shows a value of "anything" and the maxLength attribute is not there.

### Actual Behavior

Can't type "anything" since maxLength is enforced. Inspecting the input does not show a value of "anything" and the maxLength attribute is equal "0".

**Comment by sventschui** [comment]
Thanks for the report. I guess this is something to be added to the vnode normalization here: https://github.com/preactjs/preact/blob/master/compat/src/render.js#L142

Since this seems to be a beginner friendly issue I'll flag it as such and will wait a bit to see whether somebody wants to tackle it.

**Comment by developit** [comment]
The codesandbox is using old versions of Preact, but it does look like we are failing to convert `null` to `undefined` here. This can be fixed in core.

**Comment by christianpv** [comment]
I updated the sandbox to use latest Preact version. This issue is not affecting our team at the moment since we got stuck a few months ago with other issues on our transition to use preact/compat but I might tackle it by end of week if not one jumps on it. Do we want this to be fix in core or compat? @developit

**Comment by sventschui** [comment]
That would be cool! I guess core should be fine.

Sad to hear about the issues, are we talking about preact bugs/incompatibilities?

**Comment by dmail** [comment]
This bug is present with version 11.0.0-beta.1 when using `maxLength={undefined}` together with Suspense.

- Bug goes away if removing suspense
- Bug goes away if using preact 10

You can test this with this codepen (the input ends up with maxlength="0" so you can't type into it)

https://codepen.io/dmail/pen/zxNEjRz?editors=1010
