### ISSUE TITLE
Graph/Network/Node Support

### ISSUE THREAD

**Issue by EAzari** [preactjs/preact#2744]
It seems that Preact is somewhere between React and Web Components, so I have a question which I think could be a start point to build a "modern" node editor which is crucial in many areas, especially in games and CG apps

Does Preact have web features (modules/components) to build a node editor similar to [litegraph.js](https://github.com/jagenjo/litegraph.js)? especially widget nodes? and subgraphs?

![node_graph_example](https://user-images.githubusercontent.com/39350101/92462485-ca2a6b00-f1df-11ea-901f-12276a27046f.png)

CC: @ForsakenHarmony

**Comment by marvinhagemeister** [comment]
@EAzari Seems like you're a bit confused as to how all these technologies fit into the overall picture of frontend development.

- Web Components is sort-of an extension to the DOM in browsers. It's an attempt to bring some sort of Component primitive natively to browsers.
- Preact and React are frameworks that are an abstraction on top of the DOM. Their main goal is to make common problems that occur when developing web applications easier.

In the end all mentioned options allow you to build any application you want. Which one you chose is a matter of preference. Seeing that lightgraph already allows ships with a fully working node editor it's likely more beneficial to combine those technologies instead of trying to rebuild what lightgraph offers in the other options.

**Comment by EAzari** [comment]
I mean Preact has some similarities with Web Components, like props 
And some similarities with React
But I felt it's better than React and somewhat close to Web Components

But it seems that both Preact and React use Virtual DOMs but Web Components use Shadow DOMs

Let me explain my requirements, I want to be able to render (represent/present) a lot of "explicit" objects/entities/components individually on the scene (Explicit DOMs) **realtime** as well as **interactive**

About LiteGraph, I checked it a couple of months ago, and I found that around 20% of it (Widgets and SubGraph) is what we want to develop a modern node editor

And I think based on Preact its code would be lighter than the original one which uses some old approaches. For instance, its canvas grids are repeated png tile which is not suitable
