### ISSUE TITLE
Do we still need tools like why-did-you-render?

### ISSUE THREAD

**Issue by frederikhors** [preactjs/preact#2760]
I'm new to Preact.

Long time ago I was using React and it was almost necessary to use this tool to speed everything up: https://github.com/welldone-software/why-did-you-render.

Today I started working with Preact for the first time and I was wondering if today we still need a tool like that.

And if so, how can we make it work for Preact?

From here it seems to me that nobody knows how: https://github.com/welldone-software/why-did-you-render/issues/113.

**Comment by developit** [comment]
Hi there! Preact has its own developer tools that you can install as a browser extension:
https://preactjs.github.io/preact-devtools/

As for the "Why Did You Render" library, the reason there is no specific documentation on how to set it up with Preact is because it works out-of-the-box with `preact/compat`. Just [set up the aliases](https://preactjs.com/guide/v10/getting-started#aliasing-react-to-preact) and it'll print the same data it would for React.

Here's their codesandbox that I forked and dropped in the aliases on:
https://codesandbox.io/s/why-did-you-render-preact-6kcum?file=/package.json
(in the case of codesandbox the aliases are a little weird, normally it's `{"react":"npm:@preact/compat"}` or similar)

**Comment by marvinhagemeister** [comment]
> As for the "Why Did You Render" library, the reason there is no specific documentation

Even better, it's included in our devtools extension as part of the Profiler. It will record why an update was triggered. See the following screenshot :+1: 

![Screenshot from 2020-09-19 22-50-24](https://user-images.githubusercontent.com/1062408/93688982-8b8f8d00-faca-11ea-8e18-08ff799b8536.png)

**Comment by frederikhors** [comment]
@marvinhagemeister I wanna know why an update is trigger as an alert in console during development. Is this possible today?

**Comment by marvinhagemeister** [comment]
@frederikhors I'd love to hear more about the use case before adding such a feature. What kind of information you're aiming to get via the console.log output that's not present in devtools? Or are you looking for a different way to visualize renders over time?

**Comment by frederikhors** [comment]
Ok. I will explain it differently. I'm developing a new app with React/Preact.

I would love to install `why-did-you-render` or something else and during my development I have my browser's console open. When some update isn't useful I would like to see an alert (a warning, a console.log()) in my console to fix it with `shouldComponentUpdate()` or with a refac.

Is it clear now?

**Comment by marvinhagemeister** [comment]
Thanks for the explanation. That sounds reasonable, I can add such a setting to the devtools. My main worry initially was that it could get a bit noisy depending on the app in question, as I'm unsure how we can differentiate useful renders from non-useful ones. But if it's a custom user setting it's good enough imo.
