### ISSUE TITLE
Sortable react-select not work on preact

### ISSUE THREAD

**Issue by cywhale** [preactjs/preact#2790]
I tried to use react-select on preact, and it works fine. But if I want to make selected items draggable, as https://react-select.com/advanced example, it just cannot drag-drop (Multi-select is ok, but not draggable).
My Preact updated to 10.5.4.

### Reproduction
CodeSandbox: https://codesandbox.io/s/preactsortablemultiselect-u27ni
or git clone my repo
https://github.com/cywhale/preact_select_ex

### Steps to reproduce
Just run on codesandbox, or npm i && npm run dev (for git clone

### Expected Behavior
Draggable multi-selected items by mouse or on mobile (I have tried this work on React)

### Actual Behavior
Multi-select is ok, but cannot drag-drop these selected items.

**Comment by cywhale** [comment]
I found this problem is only on desktop (cannot be dragged by mouse) but work on mobile (draggable by touch). (But it works for both desktop and mobile on React app).

**Comment by sventschui** [comment]
At a quick glance I found the `preventDefault` / `stopPropagation` causing this. The problem when commenting them is that the menu popps open when dragging the items. I'll try to take a deeper look in the following days.

**Comment by sventschui** [comment]
I just took a deeper look and to be honest I'm a bit surprised this works in react. It must be due to reacts custom event system.

What happens is that the `e.stopPropagation()` called in the `onMouseDown` listener of the `SortableMultiValue` prevents the event from bubbling to the event listener of the `SortableContainer(Select)` and thus `react-sortable-hoc` never gets a `MouseDown` Event.

The following example is working, even though I'm not 100% happy with the approach as it involves a context to pass the `onSortEnd` callback: https://codesandbox.io/s/preactsortablemultiselect-forked-zw50w?file=/src/MultiSelectSort.js

Another solution without using context but some ref/`querySelector` magic: https://codesandbox.io/s/preactsortablemultiselect-forked-j6mwy?file=/src/MultiSelectSort.js

I think we can not really do something to support such a scenario as I think this is how the spec works.

**Comment by cywhale** [comment]
@sventschui Thanks! I had ever tried useContext/useRef but really don't know how to achieve these "magics" before your solutions. Save my days! I think I can close this issue and I'll update my unsolved stackoverflow with this issue link. Must someone has the same problem as me^^.
