### ISSUE TITLE
How does one modify child props in Preact?

### ISSUE THREAD

**Issue by heymartinadams** [preactjs/preact#2812]
I couldn’t find anywhere in the docs how to modify props of child components.

In my case, if the parent component `<Modal padding={true}>` has a `padding: true` prop, I’d like one of its children `<ModalContent>` to automatically also be assigned a `padding: true` prop as well (but not to some of `<Modal>`’s other children).

```js
const Modal = ({ padding, ...props }) => {
  return (
    <div {...{ padding }}>
      {/* How does one conditionally modify prop of the `ModalContent` child to include `padding: true` */}
      {props.children}
    </div>
  )
}

export default Modal
```

**Comment by marvinhagemeister** [comment]
Note that strong coupling between parent and direct children is discouraged, because it breaks the composition model of components. By doing so you'd effectively disallow consumers to use their own components.

In general there are two ways to do that:

## cloneElement

The `cloneElement` function can be used to clone a child and to pass new props to it.

```jsx
import { toChildArray, cloneElement } from "preact";

function Modal(props) {
  return (
    <div class="modal">
      {toChildArray(props.children).map((child, i) => {
        return cloneElement(child, { key: i, padding: props.padding });
      })}
    </div>
  )
}
```

The `cloneElement` approach has the disadvantage that consumers of that component can't pass in their own children anymore. Code like this will break because the props will be assigned to the `Fragment` instead of `ModalContent`:

```jsx
<Modal>
  {someCondition && (
    <>
      <ModalHeader />
      <ModalContent />
    </>
  )}
  <OtherModalContent />
</Modal>
```

## Context (recommended)

A better approach is to leverage the context api instead.

```jsx
const ModalContext = createContext({ padding: null });

function Modal(props) {
  return (
    <div class="modal">
      <ModalContext.Provider value={{ padding: props.padding }}>
        {props.children}
      </ModalContext.Provider>
    </div>
  )
}

// And then in ModalContent
function ModalContent(props) {
  const ctx = useContext(ModalContext);
  
  return <div style={...ctx.padding}>{props.children}</div>
}
```

**Comment by heymartinadams** [comment]
Herzlichen Dank, @marvinhagemeister 🙏 🎉
