### ISSUE TITLE
defaultValue not working for @material-ui TextField

### ISSUE THREAD

**Issue by masbaehr** [preactjs/preact#2954]
I noticed a difference in Render output (react vs preact) when using https://github.com/mui-org/material-ui Textfield.

In case this is due to an implementation error in https://github.com/mui-org/material-ui let me know and i will create an issue there. 
But since it is working fine in react 16 i think it's rather a preact issue.

Preact tested:   "preact": "^10.5.11",
React tested:  "react": "^16.14.0",

```javascript
import React from "react";
import TextField from "@material-ui/core/TextField";

function Debug(props) {
  return <TextField label={"Name"} defaultValue="Hello" />;
}

export default Debug;
```

Note: Changing defaultValue to "value" works, but then obviously one would have to manage the state, which defeats the purpose of defaultValue (fast typing)

**Comment by chirag-ji** [comment]
This is still not working for me.
```
"react": "^18.1.0",
"react-dom": "^18.1.0",
"@material-ui/core": "^4.12.4",
```

The `defaultValue `is still not populating, and if using `value`; getting warning

`Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components`
