### ISSUE TITLE
virtual dom crash?

### ISSUE THREAD

**Issue by bdombro** [preactjs/preact#3025]
I have an odd issue that I'm troubleshooting but am a little lost on where to start. I don't expect anyone to solve this for me, but any direction/tips would be appreciated.

I have a semi-complex Preact App with a strange behavior: occasionally the DOM stops syncing with components and never catches back up **ON MOBILE SAFARI ONLY**

Take this component for example,

```javascript
function MyComponent({someprop}) {
  return <div>{someprop}</div>
}
```

At some point during usage, `someprop` gets updated but the div.innerHTML doesn't. I confirmed this with a debugger that the function is called on prop change with the new value, so it seems like preact (aka the virtual dom) just skipped updating.

The only workaround I have so far is to location.reload() :-(

Does anyone have tips on a good place in the source code of Preact I could start exploring/stepping through to diagnose?

**Comment by marvinhagemeister** [comment]
Just checked various versions of Safari, but everything works as expected. It renders text just fine.

Are you able to narrow the problem down to a specific component in your application? One way to do that is to comment out as much unrelated code step by step (process of elimination). If the problem is reproducible in a small https://codesandbox.io/ we can take a look too.

Another thing you can try is adding `preact/debug` at the top of your main entry file (not needed if you're using preact-cli). It prints warnings and errors to the browser console for the most common usage errors. I'm in particular thinking of our injection prevention methods that skip rendering when we detect that a `vnode` (the thing returned by `createElement`), was not created by us.

In general we don't use `.innerHMTL` at all unless the prop `dangerouslySetInnerHTML` is used. Text nodes are created using standard DOM APIs instead:

```js
const text = document.createTextNode("foo");
container.appendChild(text);
```

**Comment by bdombro** [comment]
Aha! After stepping through Preact, I figured out that I was inadvertently clearing all element listeners with my method for appending the body:

Adding html to the body using this method will clear all element listeners and thereby kill Preact runtime:
```javascript
document.body.innerHTML += {SOME HTML}
```

Thank you so much @marvinhagemeister for your tips. Hopefully my sharing of my issue and diagnosis will help future people.
