### ISSUE TITLE
hooks.mjs imports @latest version of preact for direct (and oldest) versions.

### ISSUE THREAD

**Issue by vyushin** [preactjs/preact#3074]
- [ ] Check if updating to the latest Preact version resolves the issue

https://codesandbox.io/s/serverless-resonance-spus5

**Describe the bug**
Preact hooks script is importing latest version of preact for every version. It makes conflicts for instances.

**To Reproduce**

https://codesandbox.io/s/serverless-resonance-spus5?file=/index.html

1) Open https://codesandbox.io/s/serverless-resonance-spus5?file=/index.html
2) Change import version from latest to direct version (for example 10.5.13)
```
import { h, render } from "https://unpkg.com/preact@10.5.13?module";
import { useState } from "https://unpkg.com/preact@10.5.13/hooks/dist/hooks.mjs?module";
```
3) Erorr in console
![image](https://user-images.githubusercontent.com/8006957/111917647-4573b000-8a92-11eb-9120-ed4c3975b7aa.png)

**Expected behavior**
hooks.mjs shouldn't import latest version of preact for direct (and oldest) version. It should use the version actually requested

Incorrect:
![image](https://user-images.githubusercontent.com/8006957/111917704-81a71080-8a92-11eb-975a-54a7fec3cd2d.png)
![image](https://user-images.githubusercontent.com/8006957/111918288-6ee20b00-8a95-11eb-9cce-2c4862b4a200.png)
![image](https://user-images.githubusercontent.com/8006957/111918314-91742400-8a95-11eb-97f9-1331b35f3f2a.png)

**Comment by rschristian** [comment]
So that's not actually something done here. `preact/hooks` doesn't necessarily depend on the latest version of `preact`. It only lists Preact v^10.0.0 as a peerDep: https://github.com/preactjs/preact/blob/4e29ec70332c8c1c7cfb002d4069f2c9db2831f2/hooks/package.json#L20-L22 In this situation, it's up to Unpkg to choose how to supply that peer dependency, and I guess it chooses the latest version.

It might be possible to just tie the versions together, i.e., `preact/hooks` v10.5.13 has a peerDep on `preact` v10.5.13, but I don't know if that's going to pop up to cause issues somewhere.

**Comment by marvinhagemeister** [comment]
The problem is that module resolution is broken in `unpkg`. See:

- https://github.com/mjackson/unpkg/issues/281
- https://github.com/mjackson/unpkg/issues/129
- https://github.com/preactjs/preact/issues/2564

The issue has open for a long while over at `unpkg` and it's therefore probably unlikely that they'll fix it. So the only solution is to switch to a CDN that does follow the module spec. The current popular ones are either https://www.skypack.dev/ or https://npm.reversehttp.com/ .
