### ISSUE TITLE
rendering custom elements doesn't seem to work properly?

### ISSUE THREAD

**Issue by Pomax** [preactjs/preact#3230]
**Describe the bug**

Preact seems to break hard when making it render custom HTML elements (e.g. lowercase elements with a hyphen in the tag).

**To Reproduce**

1. Go to https://codesandbox.io/s/vigorous-wing-1x0fg?file=/components/app.js
2. Click on the run icon, and see it work fine.
3. remove the `tile = '';` line so that the custom element kicks in
4. Click on the run icon, get error.

**Expected behavior**

Preact renders custom elements just fine, because that's just part of the HTML spec.

**Comment by marvinhagemeister** [comment]
The error occurs because the custom element is invalid. You're calling `setAttribute` inside the `constructor` which is not permitted. It crashes with the same error in plain HTML with only native DOM functions too. The error is therefore not related to Preact.

You're likely looking for the [`connectedCallback`-lifecycle](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks). That's invoked when the element is inserted/connected to the document.

**Comment by Pomax** [comment]
Ahhh, got it, thanks!
