### ISSUE TITLE
PrismJS code is duplicated on 1st re-render

### ISSUE THREAD

**Issue by jakedee** [preactjs/preact#3236]
Code highlighted by [PrismJS](https://prismjs.com/) is duplicated after the first re-render

**Steps to reproduce the behaviour:**
1. Go to [Codesandbox - Preact](https://codesandbox.io/s/preact-prism-py8nh)
2. Click on 'Trigger re-render' button

**Expected behaviour**
[Codesandbox - React](https://codesandbox.io/s/react-prism-6y5f8)

**Comment by developit** [comment]
Hmm - this is sortof a fluke in both libraries TBH. React wipes out Prism's injected HTML because they use `.textContent` to assign the text of Elements with a single Text child. We use a different technique that is faster because it doesn't wipe content.

I believe the fix here is to set `dangerouslySetInnerHTML={{  }}` (empty) on the `<code>` element.

**Comment by jakedee** [comment]
Hi Jason, the string-to-string API sounds interesting, an example would be great!

In the meantime, I'll try implementing the changes you've suggested. Thanks!

**Comment by jpuntd** [comment]
Use the low level `highlight`  function [from the Prism API](https://prismjs.com/docs/Prism.html#.highlight) to convert your code to highlighted code:
```
const highlightedCode = Prism.highlight(
    code,
    Prism.languages.javascript,
    "javascript"
  );
```

Then display the hightlighted code inside your component. The variable `highlightedCode`  now contains the necessary html tags to do the highlighting, and for security reasons Preact automatically escapes html tags inside variables. So you'll need to explicitly opt out of this security mechanism. 
Use `dangerouslySetInnerHTML` to have the content of the  variable `highlightedCode` not escaped.
Do so only if the content comes from a trusted source!

```
return (
    <>
      <pre className="language-js">
        <code
          className="language-js"
          dangerouslySetInnerHTML={{ __html: highlightedCode }}
        ></code>
      </pre>
      <button onClick={handleClick}>Trigger re-render</button>
      <div>Re-renders: {rerenders}</div>
    </>
  );
```

Since the code is already hightlighted, you can now get rid of the useEffect call.
Adapted version of your original code, using Prism's string-to-string API can be found here: https://codesandbox.io/s/preact-prism-forked-h8lm1?file=/pages/index.js

**Comment by JoviDeCroock** [comment]
This is fixed in latest as our `render` method in compat also clears text content https://github.com/preactjs/preact/blob/main/compat/src/render.js#L87-L89
