### ISSUE TITLE
Type `EffectCallback` – allow async functions?

### ISSUE THREAD

**Issue by rauschma** [preactjs/preact#3239]
When asynchronously downloading data in a `useEffect()` callback, it would be nice if we could use an async function (whose return value would be ignored).

```ts
// Currently:
const [data, setData] = useState<null | Data>(null);
useEffect(() => {
  downloadData()
  .then((newData: Data) => {
    setData(newData);
  });
});

// Wish:
const [data, setData] = useState<null | Data>(null);
useEffect(async () => {
  const newData = await downloadData();
  setData(newData);
});
```

Current type:

```ts
type EffectCallback = () => void | (() => void);
```

Suggestion:

```ts
type EffectCallback = () => (void | Promise<void> | (() => void));
```

**Comment by marvinhagemeister** [comment]
That's interesting! Returning a `Promise` would change the semantics regarding the ability to call a cleanup function for an effect.

```js
// Sync with cleanup
useEffect(() => {
  doSomething();
  return () => runCleanup();
}, []);
```

A quick way to introduce `async/await` - albeit with a bit of verbosity - can be accomplished by using a function declaration inside the effect.

```js
useEffect(() => {
  async function foo() {
    await doSomething();
  }

  foo();
  
  return () => runCleanup();
}, []);
```

For async work the cleanup function is often a necessary requirement to be able to cancel a long-running task when a component unmounts or an effect is otherwise teared down.

```js
useEffect(() => {
  let didCancel = false;
   
  async function run() {
    const response = await fetch(...);
    
    // Abort mission if effect is already destroyed.
    // Most likely the component was unmounted at this point.
    if (didCancel) return;

    // ...continue processing
    await doSomething(response);
  }

  run();

  return () => (didCancel = true)
}, []);
```

But maybe we can have both with an async variant. Currently, we check if the return value of the effect is a `function` and assume that it's the cleanup function. If we receive a `Promise` we need another way to do that. Maybe that could be done by passing a setter to the effect function, something like this:

```js
// Pseudo code
useEffect(async onCleanup => {
  doSomething();
  onCleanup(() => runCleanup());
}, []);
```

Thinking some more about it, we could build such a thing as a custom hook that can be used without making changes to Preact itself:

```js
function useAsyncEffect(effectFn, deps) {
  useEffect(() => {
    let cleanupFn;
    effectFn(fn => (cleanupFn = fn));
    return () => cleanupFn && cleanupFn();
  }, deps);
}

// Usage
useAsyncEffect(async onCleanup => {
  // Register cleanup first, in case an `await` call throws
  onCleanup(() => runCleanup());

  const res = await doSomething();
  await doSomethingElse(res);
}, []);
```

**Comment by rauschma** [comment]
For my own purposes, this work-around was enough:

```ts
useEffect((async () => {
  // ...
}) as () => void);
```

I hadn’t considered cleanup functions; I’m not sure what’s best there.

**Comment by nmain** [comment]
> I hadn’t considered cleanup functions; I’m not sure what’s best there.

Using the custom `useAsyncEffect` hook has a bonus of giving you the flexibility of handling whatever special cleanup logic you needed.  For instance, if the original hook's promise resolved before the cleanup time, you could call one cleanup function, where as if the original promise rejected or was still pending, you could call a different cleanup function or handle cleanup in some other way.  I can imagine all sorts of creative ways to handle this...

```ts
useAsyncEffect(readyForCleanup => {
  await subscribeToMyService();
  
  // The hook implementation could resolve this promise when it's time to cleanup this hook instance.
  await readyForCleanup(); 

  await unsubscribeFromMyService();
}, []);
```

**Comment by developit** [comment]
@nmain that approach seems like it would be better-suited to generators:

```js
useEffect(async function* () {
  await subscribeToMyService();
  yield; // wait for cleanup signal
  await unsubscribeFromMyService();
}, []);
```

IMO though, all of these share a common problem that makes it unlikely to be something we'd explicitly support in Preact:  we have to be able to invoke effect callbacks atomically, and because rendering is synchronous, that requires that effect callback invocation is also synchronous.  If effects could be asynchronous, they could trigger synchronous rendering within their execution that would introduce race conditions within the renderer. Here's an illustrative example:

> An async effect callback triggers rendering of its owner component - either via setState/forceUpdate, or by invoking top-level render() on the tree. This enqueues a new callback for the current useEffect slot we are still executing.
>
> Do we clean up this effect callback before running the new one? We'd have to wait for the Promise to resolve before doing so, and its resolution may be waiting on a result produced by the newly-enqueued useEffect callback, which results in a deadlock.

**Comment by developit** [comment]
@rauschma I get the impression you may have been hinting at something dramatically simpler here though:  could we adjust the TS types of `useEffect` / `useLayoutEffect` such that returning a Promise is allowed?  I think this would be reasonable.

**Comment by rschristian** [comment]
There was a little bit of a chat on #3274 on this, but the potential for problems arising from misuse seems to be a pretty good reason to not allow this type of behavior in the TS types.

**Comment by JoviDeCroock** [comment]
After extensive discussion we've decided not to support this due to the risk of pitfalls

**Comment by ggalmazor** [comment]
Hi there! 👋 

Preact beginner here, learning the ropes. Thank you all so much for sharing insights and the link to the rejected PR, which enabled me to learn and get some context that I was missing.

I was confused by the apparent contradiction of forcing synchronous callbacks for `useEffect` while recommending the `useEffect(() => asyncStuff().then(setState)` pattern for Effects of an asynchronous nature, like updating the UI with data coming from the "outside world", e.g., live messages from other users in a chatroom.

If I understand correctly, chaining the `setState` call to a Promise is the best practice here, so I'm wondering why the Preact API doesn't promote it proactively. I guess that Effects can be used for other things beyond setting some state, but setting state feels to me like a pretty typical scenario, so I'm using this wrapper to set myself up for success in this scenario:

```typescript
const asyncUseEffect = <S extends unknown>(setter: Dispatch<StateUpdater<S>>) => (asyncEffect: () => Promise<S>) => {
    useEffect(() => {
      asyncEffect().then(setter);
    });
  };
```
