### ISSUE TITLE
Image component (next/image) of next.js aren't lazy loaded when using preactjs

### ISSUE THREAD

**Issue by thanhtoan1196** [preactjs/preact#3240]
**Describe the bug**
Image component (next/image) of next.js aren't lazy loaded when using preactjs

**To Reproduce**
Use Image component (next/image) of next.js with preactjs

**Expected behavior**
Image component (next/image) of next.js are lazy loaded when using preactjs

**Comment by marvinhagemeister** [comment]
@thanhtoan1196 Would love a bit more information, so that members from the team who are not familiar with `next` or `next/image` can take a look too. Are there any errors printed in the console? Does the image appear at all or is it loaded immediately? Can you share the snippet that shows how you are using `next/image`?

**Comment by knenkne** [comment]
Hello there, here is the same issue at Next.js repo, if u need more info I'will be glad to share
https://github.com/vercel/next.js/issues/29120

**Comment by JoviDeCroock** [comment]
This should be fixed now with this PR https://github.com/preactjs/preact/pull/3238 feel free to reopen if this is not the case
