### ISSUE TITLE
SSR Broken for CommonJS Compiled Preact Components.

### ISSUE THREAD

**Issue by davidmdm** [preactjs/preact#3277]
**Describe the problem**

SSR fails when the following conditions are met:

1) A preact component is compiled to commonJS.
2) The component uses a Hook.
3) You try to render the node with preact-render-to-string.

The error is:
```
TypeError: Cannot read property '__H' of undefined
```

Further investigation indicates currentComponent is undefined when calling `getHookState`.

**To Reproduce**

To reproduce you can clone the example repo npm install and start:
https://github.com/davidmdm/preact-cjs-example

The example uses esbuild to build/bundle a jsx component using preact to commonJS.
However using the Typescript Compiler to commonJS gives the same error.

**Expected behavior**
The compiled component should not throw an error when rendering to a string using preact-render-to-string.

**Comment by marvinhagemeister** [comment]
What's happening is that you're accidentally dealing using two different copies of Preact at the same time. The bundled file includes a its own version of Preact and then in `ssr.js` another instance of Preact is created. This is an issue because hooks conceptually require a global marker by design during rendering, but the two Preact instances don't know about each other. This is a general issue with hooks that every framework that implements them shares.

To solve this there are a two options:

1. Don't include Preact in the app bundle (easiest). This can be done by adding `external: ["preact"]` to your `esbuild` configuration
2. Generate a complete SSR bundle (this is what nextjs does). This means you have another entry point that includes the `preact-render-to-string` call and requires `app.js`. That way both use the same bundled preact instance.

Once that's done you need to update your esbuild configuration to account for JSX transpilation. The default transpiles JSX to `React.createElement()` calls, but you likely want `h` instead. To do that add the following options to your existing `esbuild` configuration:

```diff
+  jsxFactory: "h",
+  jsxFragment: "Fragment",
```

Result:

```bash
$ npm start

<div>hello world!</div>
success
```
