### ISSUE TITLE
[preact/compat] causes page to stuck when rendering radix-ui Dialog

### ISSUE THREAD

**Issue by jackyef** [preactjs/preact#3297]
- [x] Check if updating to the latest Preact version resolves the issue (tested, it doesn't resolve the issue)

**Describe the bug**
When using preact/compat with radix-ui, rendering `Dialog.Content` would cause the page to stuck indefinitely.

**To Reproduce**

[Open this stackblitz project](https://stackblitz.com/edit/nextjs-preact-webpack5-odz79y?file=components/Dialog.js), and click on the "Trigger" button to open the `Dialog`. The page should now be unresponsive.

1. Go to https://stackblitz.com/edit/nextjs-preact-webpack5-odz79y?file=components/Dialog.js
2. Click on the "Trigger" button to open the `Dialog` component
3. The page should now be unresponsive.

**Expected behavior**
The same code works with React. The expectation is that it also works with preact/compat.

**Comment by nikuda** [comment]
Related issue: https://github.com/radix-ui/primitives/issues/863

Though it's not clear which React specific features Radix UI uses.

**Comment by jas-per** [comment]
I think there is a similar issue with the latest version of react-bootstrap (see https://github.com/react-bootstrap/react-bootstrap/issues/6131)

Preact/compat gets into an endless loop when using tooltips in react-bootstrap - from what I see this could be related to the use of portals because the issues with radix-ui dialog and chakra-ui popover seem to be similar to me

would be great to get some feedback on this - having to choose bootstrap5 or preact would be a pity in the long run

**Comment by JoviDeCroock** [comment]
I mean, I don't think we'd implement synthetic events just for portals 😅 to me it feels kinda odd having to leverage DOM-events outside of a VDOM portal

**Comment by maon-fp** [comment]
We ran into this problem when using react-bootstrap, too. @JoviDeCroock If synthetic events are not to be implemented: is there an alternative?

**Comment by JoviDeCroock** [comment]
Fixed in 10.10.1 https://stackblitz.com/edit/nextjs-preact-webpack5-dmpk3a?file=package.json
