### ISSUE TITLE
Inconsistent render when rendering to non-empty root

### ISSUE THREAD

**Issue by skyh** [preactjs/preact#3503]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

Given the HTML element with the following HTML:

```html
<div id="contaner">
  <h1>Header</h1>
  <p>Container content</p>
</div>
```

When I `render(<App />, container)` I see that Preact replaces matching `<p>` element from container with App's content

```tsx
const App = () => <p>Hello from app!</p>
render(<App />, container)
```

Expected result:

```html
<div id="contaner">
  <h1>Header</h1>
  <p>Container content</p>
  <p>Hello from app!</p>
</div>
```

Actual result:

```html
<div id="contaner">
  <p>Hello from app!</p>
  <h1>Header</h1>
</div>
```

I noticed when I use different tag (`section` instead of `p`) than I see expected behavior

```html
<div id="contaner">
  <h1>Header</h1>
  <p>Container content</p>
  <section>Hello from app!</section>
</div>
```

**To Reproduce**

1. Open codesandbox link https://codesandbox.io/s/staging-sunset-lj9ljz
2. See `<p>` content from App and no content from container HTML

**Expected behavior**
Both content from container and from App should be rendered.

**Comment by marvinhagemeister** [comment]
Preact expects to have full ownership of the contents of the container that's rendered into. The `render()` function is not built to patch any kind of DOM tree on to match the expected virtual tree. It's meant to be used on an empty container. The `hydrate()` function is an exception to that, but it requires the DOM-tree to match 1:1 to the virtual tree.

We do have some code in place to work around oddities caused by Google Translate inserting elements with `render()`, but other than that the scenario you're trying to accomplish is not supported. It's very unlikely that we'll support it in the future as it opens a can of worms of edge cases to account for.

**Comment by danielweck** [comment]
Hello @skyh 
You might also like to read this:
https://gist.github.com/developit/f4c67a2ede71dc2fab7f357f39cff28c

**Comment by andrey-ivlev-qs** [comment]
Thank you for clarification.
