### ISSUE TITLE
v11 ability to specify render() order in parentNode's children

### ISSUE THREAD

**Issue by Colisan** [preactjs/preact#3542]
Hi, in [the current documentation](https://preactjs.com/guide/v10/api-reference/#render) it's written that

> The replaceNode-argument will be removed with Preact v11

But no replacement is specified. What is the new way to tell, for example "render this vnode between the 4th and the 5th child of this parent dom element"? I don't see any parameter to render() that currently allow such a configuration.

If already determined, can we add this information into the documentation?

**Comment by danielweck** [comment]
Try this :)

https://gist.github.com/developit/f4c67a2ede71dc2fab7f357f39cff28c

**Comment by developit** [comment]
Heh, thanks @danielweck as always :)

We'll include a nice guide and shim library based on that gist with the 11 launch.

**Comment by MicahZoltu** [comment]
I would like to make sure this doesn't get dropped, but I'm not sure how.  As I understand it, this is still an issue 2 years later (at least, v10 still says deprecated and still points people at that gist I believe), but the code doesn't actually pass type checking (it is passing incompatible objects into into functions) and, worse, it directly references preact internal properties which means if those property names ever change anyone using this code will break.

Is the idea that v11 will provide a properly implemented function with a signature of
```ts
createRootFragment(parent: ContainerNode, replaceNode: ContainerNode | ContainerNode[]): ContainerNode
```
and users who are using the code in the linked gist are basically just using a shim that only needs to work until v11 is released, at which point they'll just delete the shim code entirely and import the function with the same name from v11 library?

The code was recently published to https://github.com/preactjs/preact-root-fragment, suggesting this is in fact a final solution and it says it is compatible with Preact 11 suggesting that people will be expected to use this code long term.  However, this published version contains all of the same problems as the gist which is concerning.

Perhaps the issue is that Preact's types are wrong, and this library just lies about the types to work around it?  Any chance of fixing preact's types if that is the case?

Is there any way to avoid referencing internal preact properties (which I think may be post-mangled names even)?

**Comment by rschristian** [comment]
> v10 still says deprecated and still points people at that gist I believe

Yep, only just made the repo public. Will update that comment shortly though, it's on my to-dos.

> but the code doesn't actually pass type checking (it is passing incompatible objects into into functions) and, worse, it directly references preact internal properties which means if those property names ever change anyone using this code will break.

Preact's internal properties are entirely stable and they're something our first party ecosystem relies upon _very heavily_. Don't worry, we maintain them safely. They are not changed between majors and the last ~6 years of Preact X is proof of this.

As for the lib, are you referring to it not passing type checking, or user code not passing? It not passing shouldn't really be a concern. If user code fails please open an issue.

> Is there any way to avoid referencing internal preact properties (which I think may be post-mangled names even)?

No, the interface relies upon it.

**Comment by MicahZoltu** [comment]
The internals of the library are impossible to satisfy according to TypeScript.  For example, in the library it references `nextSibling` on `ContainerNode`, but `ContainerNode` doesn't have a `nextSibling` property on it so this *should* fail at runtime.  That it doesn't suggests to me that either this function doesn't actually want a `ContainerNode` (it wants a `Node`), or the type definition for `ContainerNode` is wrong.

Same problem exists for all of the properties on the object being passed to `__k` (which appears to be a `ContainerNode`.  `.parent` on that expects a `ParentNode`, but a `ContainerNode` is not a `ParentNode` anymore than it is a `Node`.  Same problem exists for all of the properties assigned on the `__k` object.

My suspicion is that the type definition of `ContainerNode` is wrong and perhaps in reality it extends `ParentNode` or `Node`, which I think may fix most of the problems.  If this is the case, then the red flag for me here is that this little library caused me to realize that the public facing type definitions for preact are wrong and it would be great to see them fixed.

Regarding my actual scenario, I would prefer to just put this code into my project directly rather than pulling in an entire NPM package for ~30 lines of code (every package increases security/audit surface area), but I cannot at the moment because the code won't compile in my project.

**Comment by rschristian** [comment]
> The internals of the library are impossible to satisfy according to TypeScript.

I'm sorry, but what is the issue there? That we don't appease TS internally? Internal type errors, to my knowledge, shouldn't ever show short of cloning the repo or manually opening the file in your editor. TS shouldn't typecheck JS files from within `node_modules`.

>  If this is the case, then the red flag for me here is that this little library caused me to realize that the public facing type definitions for preact are wrong

It's definitely possible, though no one has raised any issues about it (AFAIK). Certainly, if you have any issues from user land, or suggestions to improve the types of Preact or that lib (without sprinkling casts or creating new intermediary vars just to appease the TS lang server), then we'd absolutely be grateful to hear about them.

**Comment by MicahZoltu** [comment]
I think the core of the issue is that when this was deprecated it was implied that people could still achieve the same results with a handful of lines of code in their project.  The gist was created that showed such code, but it has consistently failed to work in TypeScript projects without lying to the compiler (e.g., `as any as Foo`).

Eventually it was turned into a library (today) which works around the issue by just having the library itself lie to the compiler and leaving the implementation in untyped JS.

From your responses, the impression I'm getting (please correct me if I'm wrong) is that the code provided as a workaround is not something that is intended to be something that works in preact user codebases?  The gist was meant as a temporary workaround until the recently released library was published, and people should no longer attempt or expect to be able to author code like this in their TS projects?

If it was intended to be code that a preact user could author, then it should compile against the public surface API of preact, without needing access to internal variables (which aren't expressed in the preact type definitions from what I can tell) and without needing to cast things just to get it working.

If my new understanding is correct that this isn't something that it is intended a user should be able to author, then I think there is nothing more to do.  If the intent is that this should be code that a user could author, then this library can serve as a sort of test case that shows there are some bugs in the TypeScript definitions and such bugs should probably get tracked somewhere (which is why I raised my recent concern).

**Comment by rschristian** [comment]
> From your responses, the impression I'm getting (please correct me if I'm wrong) is that the code provided as a workaround is not something that is intended to be something that works in preact user codebases? The gist was meant as a temporary workaround until the recently released library was published, and people should no longer attempt or expect to be able to author code like this in their TS projects?

The Gist was always set up to be a drop-in prior to the release of a lib, hence why it has a `package.json`, yes. However, you can copy/paste that lib and slap a `// @ts-ignore` comment in there if the squiggles are a problem. The underlying language is dynamically typed and we do make use of that from time to time; TS artificially restricting that isn't super compelling (IMO).

> then it should compile against the public surface API of preact, without needing access to internal variables (which aren't expressed in the preact type definitions from what I can tell)

Sorry, but passing the TS compiler has never been a guarantee we provide with some of our functionality. Our properties have stable mangling, and you may want to make use of it from time to time, but we don't (and I believe can't) provide types for it in all situations. There is a lot of very valid Preact code that TS will reject which we generally treat as acceptable.

Some of our libs have defined internal types to suppress internal errors, some do not, but for user code it's mostly up to the user to decide how they want to deal with that.

They're still a user-facing feature, just not one that TS will agree with all the time.

**Comment by marvinhagemeister** [comment]
To add to this: we tried several times to make the preact internals fully type safe as measured by the TS compiler but always ran into the same issues:

- DOM types are not as well maintained as altoher areas of TS
- Due to that we'd need to add a lot of type guard functions to aid TS in narrowing down types.
- adding those aids lead to a performance regression that wasn't in the acceptable boundaries anymore 

It sounds like you're quite experienced with TS and have a good feel for TS. Maybe you can be the one who manages to find a solution for this? We'd be more than happy to look at PRs.

**Comment by MicahZoltu** [comment]
I appreciate the offer/suggestion and I may try to take a crack at it at some point, but unfortunately I am quite busy with many other projects, so it is unlikely I'll get to it.  I think the last two comments in this thread have answered my question and helped me fully understand the situation.  I appreciate the patience from both of you!
