### ISSUE TITLE
Usage without client side state

### ISSUE THREAD

**Issue by avin-kavish** [preactjs/preact#3637]
**Describe the feature you'd love to see**

I would like to use preact without any client side features and purely for server side rendering. So is there a way to turn off stateful features? e.g. prevent the user from using hooks etc

**Comment by JoviDeCroock** [comment]
Hmm, this does seems to lack a bit of information as this is already possible. You can statically generate your HTML (or server-side generate it) and not include your `<script>` tag. This will make it so that you send down HTML which will function with `<a>` tags and so on but won't hydrate in hooks etc, this comes down to just not giving an entry point for the user when it's leveraged on the client, no JS, no Preact.

**Comment by avin-kavish** [comment]
Right, yeah. Let me get into some detail. What I want to do is restrict stateful code being written. I'm not the end user, I'm writing a library with preact.

```ts
function Counter() {
  const [value, setValue] = useState(0);
  const increment = useCallback(() => {
    setValue(value + 1);
  }, [value]);

  return (
    <div>
      Counter: {value}
      <button onClick={increment}>Increment</button>
    </div>
  );
}
```
So if a user writes this, this will render on the server but if I don't include the script tags it won't be interactive on the client side as they expect. So I want to throw an error early to inform them this won't work.

**Comment by avin-kavish** [comment]
Actually, more I think about it, I think I will be adding client-side hydration anyway, so this seems unnecessary.
