### ISSUE TITLE
"Cannot read properties of null (reading '__')" error when suspending the entire app

### ISSUE THREAD

**Issue by theninthsky** [preactjs/preact#3647]
Preact version: `10.10.1`.

**Bug Description**

When wrapping the entire `<App>` with Suspense, I get the following error:

```
Uncaught TypeError: Cannot read properties of null (reading '__')
    at i.__c.shouldComponentUpdate
```
And almost the entire app unmounts (due to the lack of error boundary).

This **does not** happen if I only wrap the `<Routes>` component with Suspense.

**To Reproduce**

1. Clone my repo: https://github.com/theninthsky/client-side-rendering/tree/preact.
2. Execute `npm i` and `npm start`.
3. Refresh the page a few times until this error shows.

You can even visit the preview deploy here: https://04cb527b.client-side-rendering.pages.dev

**Expected behavior**
No error should be thrown and the app should be visible.

**Comment by marvinhagemeister** [comment]
Spent a bit debugging this and the issue is caused by this line:

https://github.com/preactjs/preact/blob/191d5cb204eb12cb8791f44a04e2b23712795ade/compat/src/suspense.js#L51

Still looking for what would be a proper fix.

**Comment by JoviDeCroock** [comment]
We might want to edit [this line](https://github.com/preactjs/preact/pull/3645/files#diff-c580d3b3982d2cf5341923532890e75fceb15c1fd1e7993f9b7ba897e3dbe2e1R188) to return true when there are no __hooks the issue is the resetting logic we need to alter for suspenseful components, I wrote about this a bit [here](https://hallowed-fear-993.notion.site/Suspense-ca56619215544859ac40582bae8c32a3)

We fixed this issue once before but I forgot about it with that last pr, last fix: https://github.com/preactjs/preact/pull/3643

**Comment by theninthsky** [comment]
@JoviDeCroock 
Works great, thanks!

**Comment by JoviDeCroock** [comment]
@theninthsky thanks for following up, happy to hear that and apologies for breaking this twice in a row 😅
