### ISSUE TITLE
DevTools do not work with the new Deno framework, Fresh.

### ISSUE THREAD

**Issue by moonstripe** [preactjs/preact#3686]
**Describe the bug**
When making a Fresh application, adding "import "preact/debug"" to the entrypoint of the application does nothing. The Fresh framework relies on preact by default, so it should work?

**To Reproduce**
1. Create a new Fresh
```
deno run -A -r https://fresh.deno.dev my-project
```
2. Insert `import preact/debug` to the top of main.ts (entry point for production) and dev.ts (entry point for development).
3. Go to `localhost:8000/` and check the Preact DevTools Extension.
4. It will say "This page doesn't seem to be using Preact. // Import preact/debug somewhere to initialize the connection to the extension. Make sure that this import is the first import in your whole app."

**Expected behavior**
I should be able to view the devtools if I've downloaded the extension and place `import "preact/debug"` into the entrypoint of the application.

**Comment by marvinhagemeister** [comment]
Took a look at that and fresh does some custom bundling logic. Both the `main.ts` and `dev.ts` entry point fresh exposes run on the server and not in the browser, which is why including the `preact/debug` import there does nothing. It needs to be included in the actual bundles that are served to the browser.

Made a PR to fresh that includes `preact/debug` in the browser bundle automatically whenever dev-mode is active. See: https://github.com/denoland/fresh/pull/639 .

Closing as it's not an issue with Preact itself, but the way fresh generates the browser bundles. Follow the PR on the fresh repo for more information.
