### ISSUE TITLE
Question: reason for error with 3rd party

### ISSUE THREAD

**Issue by cherepanov** [preactjs/preact#3798]
Trying migrate to Preact. One stopper for now is 3rd party component which produces error.
For now very new to Preact and have no idea where to start digging.
What does it look like and what could be cause of this error?

Issue in component repo https://github.com/swagger-api/swagger-ui/issues/8282

```
debug.js:328 Uncaught Error: Objects are not valid as a child. Encountered an object with the keys {size,has,get,__iterateUncached,__iteratorUncached}.
```

**Comment by marvinhagemeister** [comment]
This error is thrown to prevent json injection attacks when somewhere an untrusted object is passed as if it was a JSX element created by Preact. In this case it looks like swagger is passing class instances from immutable-js directly into JSX without calling `.toArray()` first to unpack them at some places.

This works in React because they added support for rendering any iterable that is passed to JSX with I think 16 or 17 (memory is a bit fuzzy). Afaik it was never an officially supported feature and it's the first time I'm seeing someone rely on it outside of demo code.

The best option is to solve this on the swagger-ui end.

If you don't want to wait you can always change properties on the fly in Preact via an `options.vnode` hook and sort of polyfill in automatic unpacking of immutable-js class instances.

```js
import { options } from "preact";

const oldVNode = options.vnode;
options.vnode = (vnode) => {
  // This code automatically unpacks immutable js instances when they
  // have been passed as JSX nodes.
  if (
    vnode.type !== null &&
    vnode.props &&
    typeof vnode.props.children === "object" &&
    vnode.props.children !== null &&
    vnode.props.children.constructor !== undefined &&
    typeof vnode.props.children.toArray === "function"
  ) {
    vnode.props.children = vnode.props.children.toArray();
  }

  if (oldVNode) oldVNode(vnode);
};
```

**Comment by cherepanov** [comment]
Thx! Now its clear for me. 
Swagger-ui is a mess, will stick this workaround for while.

@marvinhagemeister Just curious why this not implemented in Preact?

**Comment by JoviDeCroock** [comment]
Closing this as an external issue
