### ISSUE TITLE
Typescript:  input property indeterminate is not typed

### ISSUE THREAD

**Issue by nattthebear** [preactjs/preact#3836]
**Describe the bug**
When using Preact with typescript, the `indeterminate` property on checkboxes cannot be set.  This is a type-only issue, as the property works correctly in the browser.

**To Reproduce**
Typescript playground:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAIjFApgQwMYwQbgLABQokscASulnAGZQQiLKUwD0G9YarAzlBroUIsWcAGJpgAG25wYEWQE8wKDAAsVAazgQAdnAAKqTPABSAZQAahADzAdYAK7wYSlAF4EazQCMIADwQ4OwATFBgUKBA7LhQ4FgA+QQJhOAAVVy8MDRlkCGUoSQVtPRh1OFQAcwdJNCg4ABEAeQBZIJ1wqGpMFG5CUIwa1DgAN1q2xxgAUUkALjgACVTmgBkASXsnaZQQFHb8Ig2pyQA6ELCIqJ0Y-aA

**Expected behavior**
The above code should be accepted by the typechecker.

**Comment by rschristian** [comment]
I'm not entirely sure this should be supported, FWIW.

`indeterminate` cannot be set via HTML attributes, so attempting to set it in JSX feels a bit off. It doesn't look like React's types support doing this either.

**Comment by nattthebear** [comment]
React prefers property names over attribute names when both are available (`tabIndex` vs `tabindex`, `className` vs `class`, etc.).  Preact is less opinionated.  But both frameworks generally support setting either in most case, differentiating by a [property existence check](https://github.com/preactjs/preact/blob/master/src/diff/props.js#L118), so I think both should be reflected in types when reasonable.

**Comment by rschristian** [comment]
Sorry, I might not have been clear.

`indeterminate` is a bit of a special property, as it has no corresponding HTML attribute; therefore, attempting to use it in JSX (HTML in JS) feels a bit questionable to me.

As React also does not support using `indeterminate` in JSX to my knowledge, this feels like a thing that should be handled with refs even if JSX is compiling to something that can support DOM properties instead of HTML attributes.
