### ISSUE TITLE
Pass inEvent argument to a custom debounceRendering function

### ISSUE THREAD

**Issue by NatteeB** [preactjs/preact#3902]
Is it possible to pass the _inEvent_ flag into the _options.debounceRendering()_ hook or export the flag to the application?

This request is related to the recent change ‘[use microtick outside of events](https://github.com/preactjs/preact/pull/3879)’. With this change the internal _defer()_ call uses either timeout or microtick based on the _inEvent_ flag. We want to mirror this logic in our custom _options.debounceRendering()_ override but our custom override needs to be aware of the value of _inEvent_ flag.

We use the custom _debounceRendering()_ method for automated testing to detect when the rendering queue is complete. We don't want to change the timing approach used by Preact, we just want to inject some additional logic required by our applications.

**Comment by jramanat-oracle** [comment]
@JoviDeCroock (Filer and I are co-workers)

One additional consideration here, which unfortunately I didn't get a chance to add to the issue before you had already resolved it, is whether there might be any concern from the Preact side to exposing this flag and potentially tying the API signature of the debounce hook to this flag which was only recently added.  Any worries about future changes in this area which might obviate the need for this flag and then potentially lead to a breaking API change?

Another possibility we had discussed which would also solve the problem we were facing would be if Preact simply exported its default implementations for these timing-related options.  I think this would be the defer() function in src/component.js (for options.debounceRendering) and the afterNextFrame() function in hooks/src/index.js (for options.requestAnimationFrame), presumably renamed for export.  That would still allow us to inject our own custom logic, by wrapping the callback function before delegating to the original implementation, but still allow Preact to retain full flexibility to change the inner workings of these functions if desired.

Apologies for not getting this comment in sooner (and your current fix is certainly workable from our side), but wanted to at least mention this alternative in case it's more desirable from the Preact side before this API goes out in the next release.  Thanks!

**Comment by JoviDeCroock** [comment]
@jramanat-oracle my personal preference would be to not expose a mutable variable or the methods we use in the different sub-packages due to the byte-size impact this would have 😅 that however is a personal preference and I'm up for more opinions on that aspect. The main reasoning behind exposing these hooks is so people can use their own scheduling which deviates from ours, it's the first time I actually hear about one that builds on ours.

**Comment by jramanat-oracle** [comment]
Ha, fair enough!  Selfishly, I think exposing the default implementations would be more convenient for our case, where we're just trying to track when there is pending Preact work (the hook is called) and when it's complete (the callback is invoked), since it would save us from having to make code changes to stay in sync when Preact's default behavior changes.  That said, I'm sure you're correct that the much more common case for using these hooks is to change the timing behavior and the default implementations are of no use for that case, but potentially the inEvent flag might be?  I don't have much intuition regarding how others might be tweaking the timing functions and how specific they'd want to get.

**Comment by JoviDeCroock** [comment]
We are def going to give you the `inEvent` flag 😄

**Comment by jramanat-oracle** [comment]
Sounds good, thanks for the discussion!
