### ISSUE TITLE
v 10.13.2 broke my jest snapshot tests. Attribute order changed.

### ISSUE THREAD

**Issue by corinnaSchultz** [preactjs/preact#3972]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I attempted to upgrade from preact version 10.13.0 to 10.13.2 and my jest snapshot tests failed. Using version 10.13.1, they all pass.  Perhaps PR #3948 had a side effect of changing the rendering order of attributes?

**To Reproduce**

Use version 10.13.0 to create snapshots with jest. Make sure your components have attributes.
Re-run your jest snapshot test with 10.13.2

Example:
My original snapshot:
`"<button class="closeButton light" aria-label="Cerrar"><mockasset></mockasset></button>"`

The new one that failed the test:
`"<button aria-label="Cerrar" class="closeButton light"><mockasset></mockasset></button>"`

At first I thought the attributes were being put into alphabetical order, but some of my snapshot failures are not in alphabetical order.  It appears random.

Example:
My original snapshot:
`<div class="errorsWrapper" role="alertdialog">`

The new on that failed the test:
`<div role="alertdialog" class="errorsWrapper">`

**Expected behavior**
What should have happened when following the steps above?

I would not have expected the snapshots to be rendered differently.

**Comment by andrewiggins** [comment]
Unfortunately we can't guarantee the order of attributes when serializing, and could change due to other libraries, not just Preact. For example, changes to browsers, jsdom, preact-render-to-string, or JS engines could also affect the order of attributes upon serialization.

Something we do in Preact to make our serialization tests a bit more resilient in places where we've noticed some difficulty in reproducing consistent HTML (mostly due to browser inconsistencies) is to [sort attributes](https://github.com/preactjs/preact/blob/7adb1473fc1c0d306bea81a37e2c1e8528184674/test/_util/helpers.js#L243-L258) after serializing but before comparing to the expected output. Could doing something similar work for you?

I haven't looked, but if you are using Jest, I wonder if there is a jest snapshot plugin that does this for you when serializing HTML... If not, that'd certainly be very useful to have I think!

**Comment by corinnaSchultz** [comment]
Those are some good suggestions. I think jest has a prettier for snapshots. I'll look into that. Thanks!
