### ISSUE TITLE
Problem with rendering child component on props changes

### ISSUE THREAD

**Issue by coder4u** [preactjs/preact#4279]
**Describe the bug**
There was a problem with the rendering of components when updating props.
If you pass the state of a parent component as a prop to a child component, and then update the state in the parent component, the child component is not rerendered.

**To Reproduce**
Preact - https://codepen.io/coder4u/pen/YzgdQEL

React without rerender issue - https://codepen.io/coder4u/pen/qBvLXOy

1. Go to pen.
2. Open console.
3. You will see that parent state not synced with child props in render methods.

**Expected behavior**
Child component must rerender when it props changed.

**Comment by JoviDeCroock** [comment]
Looks like this got broken between 10.18.1 and 10.18.2

**Comment by dmitrage** [comment]
Did some debugging, maybe it could help.

When `BrokenChild` is rendered for the first time its `vnode._original == 3` (++vnodeId).
After `setState` in `BrokenChild.componentDidUpdate` it [increments](https://github.com/preactjs/preact/blob/65310c6c6f8445b531c47b188431385a80a1d104/src/component.js#L130) to `4`. Note that global `vnodeId == 3` at this time.
When `App` component re-renders after `setTimeout` it creates a new vnode for `BrokenChild` with `_original == 4` (++vnodeId).
Then rendering bails out because `oldVNode._original == newVNode._original`.

Before the [mentioned change](https://github.com/preactjs/preact/pull/4171) `_original` was changed on a temporary copy of the oldVNode but now it is changed on the newVNode.

**Comment by JoviDeCroock** [comment]
Yeah, I got to a similar conclusion, we might just need to change the `vnodeId` back after diffing 😅
