### ISSUE TITLE
`render()` called with reused JSX not triggering Component re-render

### ISSUE THREAD

**Issue by colinaaa** [preactjs/preact#4509]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

When a JSX is reused between multiple `render()`, the Component within it will not be called unless using `cloneElement()`.

**To Reproduce**

Add the following code in `render.test.js`:

```js
	it.only('should allow VNode reuse at root', () => {
		let text = 'Hello World!'
		function Foo() {
			return <div>{text}</div>
		}
		let reused = <Foo />;

		render(reused, scratch)
		expect(serializeHtml(scratch)).to.eql(`<div>Hello World!</div>`)

		text = 'Hello Preact!'

		render(reused, scratch)
		expect(serializeHtml(scratch)).to.eql(`<div>Hello Preact!</div>`) // Failed here
	})
```

Note that adding a `cloneElement()` would fix this problem:

```diff
- render(reused, scratch)
+ render(cloneElement(reused), scratch)
```

**Expected behavior**
What should have happened when following the steps above?

`Foo` should be called and `Hello, Preact!` should be rendered.

**Comment by JoviDeCroock** [comment]
This is referred to as strict equality, this is a bail we have created in Preact for i.e. children passing optimizations. This is expected behavior https://github.com/preactjs/preact/blob/main/src/diff/index.js#L150-L187 - some more info can be found here  https://gist.github.com/JoviDeCroock/bec5f2ce93544d2e6070ef8e0036e4e8

**Comment by colinaaa** [comment]
Got it! Thanks for your explanation.
