### ISSUE TITLE
types: `href` missing from SVGAttributes

### ISSUE THREAD

**Issue by birtles** [preactjs/preact#4574]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
10.25.0 adds stricter typing for element attributes (#4546) but it omits `href` from `SVGAttributes`.

**To Reproduce**

Write content such as:

```jsx
function Hello() {
  return (<use href="#abc" />);
}
```

Perform type checking.

**Expected behavior**

Type-checking should not return an error.

In SVG the `<use>`, `<foreignObject>`, `<image>` and `<script>` elements can have an `href` attribute.

Many many years ago `href` needed to be in the `xlink` namespace but browsers have supported bare `href` for about a decade or so now.

**Comment by rschristian** [comment]
Thanks!

For what it's worth, no justification is necessary -- it was a mistake, nothing intentional. In the past, `SVGAttributes` extended from a mega interface of all HTML attributes, which of course included `href`. Since 10.25, however, it only extends from an interface of truly global attributes/props, which `href` is not included in.

`xlinkHref` (and `xlink:href`) are SVG-only (to my knowledge) so they were already in the SVG interface is all.

**Comment by birtles** [comment]
Great, thank you so much!

**Comment by rschristian** [comment]
No problem! Certainly let us know if you spot anything else out of the ordinary -- it was a big change, hopefully for the better, with a lot of surface area for slip-ups. We did our best to try to minimize these by checking out various repos but there's always the possibility of combinations/attributes we didn't encounter.
