### ISSUE TITLE
Support Asynchronous Components

### ISSUE THREAD

**Issue by neeharv** [preactjs/preact#526]
Inspired by https://twitter.com/youyuxi/status/824659082816716802

It'd be great if we could do the same with Preact. Looking forward to a discussion about what would it take to add support. Off the top of my head, this would possibly need

1. Async rendering support
2. Caching of ^ so subsequent renders are immediately resolved
3. Update `h` to support Promises as children

A common argument against this would be to have this in userland code, however there are legitimate cases where having this baked into the framework itself would strongly encourage developers to start using code-splitting, which I think fits into Preact's goals of performance and min size.

**Comment by developit** [comment]
Love the idea, but I can't think of a way to implement this that would work in Preact's core.

**Comment by thysultan** [comment]
@developit, depending on how you implement forceUpdate, if `import` returns a promise... you could just replace the render method with one that returns the cached response while rendering an empty element.

```js
.then((value) => {
    component.constructor.render = component.render = () => {return value} ;
    component.forceUpdate;
})

return h('noscript');
```
and end with calling forceUpdate once the promise has resolved.

**Comment by developit** [comment]
That's quite similar to how the userland solutions work actually (implemented this today!)

**Comment by developit** [comment]
The handling would go [here](https://github.com/developit/preact/blob/master/src/vdom/component.js#L45), but honestly the whole chain to that point is synchronous without #409 being merged yet.

**Comment by Satyam** [comment]
I would like to suggest to add the ability for `componentWillMount` and `componentWillReceiveProps` to return a Promise, in which case the rendering would be delayed until the Promise is resolved.  I meant to offer a working example and I modified [setComponentProps](https://github.com/Satyam/preact/blob/async-lifecycle-methods/src/vdom/component.js#L19) and tried to make some [examples](https://github.com/Satyam/preact-async) to show it working but, unfortunately, due to my lack of deep knowledge of Preact, failed to make it work.  

The Readme file on the [example](https://github.com/Satyam/preact-async) code explains what I tried to do and how to use it.   

The existing tests on the modified Preact run fine, so the change is backward compatible.

I am sorry I am new to Preact, I hoped I could be more helpful.

Thanks

**Comment by Satyam** [comment]
I am guessing here but I imagine that what I need to do is pile up all the promises returned from `componentWillMount` and/or `componentWillReceiveProps` and then make the diffing of the new vdom against the existing run on a `Promise.all()` of all these pending promises. If the array is empty, the diff would run right away, otherwise, it would wait until all the renders, either synchronous or queued, are done.  I am still trying to find my way over this code, any ideas as to where to look?  Or whether I'm on the right track?  Thanks again.

**Comment by developit** [comment]
@Satyam It would work the same way as #409 really. That said, I'm not sure I follow what async `componentWillMount()` would give us?  By that point we've already instantiated the component, so the cost has been paid (same deal for `componentWillReceiveProps()`).  Paul's PR introduced the idea that we could defer even instantiating a component until there were free cycles to do so, which I think is the only effective way to defer work (unless I'm missing something?).

**Comment by Satyam** [comment]
@developit If I am not reading it wrong, the idea of #409 is that, if new data arrives when the components are rendering, interrupt them and start with the new data.  What I mean to do is that instead is to hold on until the data is there.  Specially in SSR, you only have one chance with `res.send()` so when it happens, it better be good.
In both the methods I suggest changing, `this.props` is already populated and components can go and fetch the data they really need. And they can render the children they actually need, like the todo-item components in a todo-list, if you don't wait for the data, how could you know which children to render?  Doing it in the traditional way it requires the developer to somehow device ways to fetch the data based on the URL so that everything is there before attempting to call `renderToString`. If you do it when mounting then you are using the same logic (routing, conditional rendering, etc) that your application will use.  Since data fetching can take a while, it serves no purpose to optimize a make-do rendering that will have to be discarded.  If the waiting time is mostly in fetching the data, optimizing the render makes no difference, better to wait and do it right. I want to render based on actual data, not on the availability of free cycles.

**Comment by developit** [comment]
The key with Paul's PR is as you described:  components are progressively instantiated as CPU is available - they won't even be invoked/rendered/anything until the scheduler kicks in. This is useful because it means if your data fetching beats the progressive rendering, your first render will be with the fetched data, so nothing is wasted.  If CPU time is available before data comes in, components will be "booted" and can show a UI indicating loading.

More generally though, it seems a little bit odd to fetch data on the server and do a synchronous static render, but then also re-fetch that same data on the client to do an asynchronous render that likely produces an identical DOM tree.  Most people who do full SSR as you describe also send down the data to be used for hydration, so that components boot into a cached state instead of a loading state.  Maybe that would be a simpler approach?

The problem with making any of the lifecycle methods truly asynchronous (eg: promise-returning) is that it introduces a very real locking issue - if a (parent) re-render is triggered while a component is in an unbooted state, does it boot?  If the DOM is mutated outside the control of Preact before a component has booted - is that left in-place somehow (impossible to know that it happened), or is the now mismatched DOM mutated to match the initial render of the component?

These are a couple of the main reasons VDOM libs don't tend to rely on asynchronous lifecycle methods, rather choosing to implement asynchronicity internally within the diffing algorithm.  When internally implemented, it can be halted or cancelled.

That said, #409 has been a long time coming because I'm trying to integrate a pluggable scheduler into it.  That would allow you to write a simple scheduler that asks components when they would like to boot, which I think is a very elegant solution to the issue you laid out.  You'd define a static method on your components (something like next.js' `getInitialProps()`) that is given control over the initial boot of the component.  Until that method's returned Promise resolves, the component is left unbooted and any SSR'd DOM left in-place.

**Comment by scurker** [comment]
> More generally though, it seems a little bit odd to fetch data on the server and do a synchronous static render, but then also re-fetch that same data on the client to do an asynchronous render that likely produces an identical DOM tree.

It might seem a little odd to want to do this, but there are some very practical user benefits from doing so. Given that javascript can be blocking for a number of different reasons (network, parsing, etc.) by providing an initial SSR state that is already valid, you can ensure that the user already has content ready to go regardless of the current state of javascript. In a more real life example, we had an issue with our CDN recently where assets were taking upwards of 5 second to download over a fast wifi connection. Had we not had valid async SSR content delivered, it would have had an adverse impact on our users. It didn't matter that the content eventually got rehydrated with an initial state _because it was already valid_.

**Comment by developit** [comment]
Isn't that just display content though, with no interactivity?
FWIW I didn't mean to dismiss the approach, just that is one reason I've avoided it. I also don't do much SSR either so I'm in a bit of a minority, haha (I just do prerendering and deploy everything to CDNs)

**Comment by scurker** [comment]
Correct. It's a bit of uncanny valley since the time to interactive is still delayed until after scripts, but some content is better than no/placeholder content until after blocking javascript.

It's an approach that has unfortunately been left to userland, so there's a lot of haphazard magic to sometimes make it work correctly. And unfortunately I think some people tend to avoid it because of the potential difficulty. Maybe Async SSR is a whole other issue, so I don't want to commandeer this issue, it's just been something on my mind.

**Comment by developit** [comment]
You might find this thread interesting - it's a super simple full async SSR:

https://github.com/developit/preact-render-to-string/issues/30#issuecomment-288874846

**Comment by Satyam** [comment]
@developit 
>  it seems a little bit odd to fetch data on the server and do a synchronous static render, but then also re-fetch that same data on the client to do an asynchronous render that likely produces an identical DOM tree

It is not my intention to do that. As I mention towards the end of [this section](https://github.com/Satyam/preact-async/blob/master/README.md#what-if), a Redux store could be populated and it serialized contents sent to the client, where it can be re-hidrated.  Though a developer my blindly query the source for data when invoked, it would be sensible to check whether the data is already there and, if it is already available (from the SSR rendering or whatever) the Promise would be resolved immediately.  In the end, whether the developer does this or not is no argument against the feature being available.  The examples shown in my sample code are oversimplified, I normally use Redux and hardly ever fetch data blindly.

I defer to you regarding the locking and refreshing issues, if that is a show-stopper, then there is no further discussion.

I don't mind if existing methods are repurposed as I suggest or a new `getInitialProps` method is defined.  I don't agree on it being static as you suggest as the purpose of it is to do whatever it does based on `this.props` and possibly `this.state`.  Of course a static method could receive `props` and `state` as arguments, as `render` does, but then it departs from the standard of other lifecycle methods.  I don't mind adding `props` and `state` as sugar, but making that the only means of accessing them promotes the already too frequent overuse of `this.state` for storing all information which might not always require a refresh and taxes the application with pointless rerenders due to changes to `state`.

However, I do prefer to have `componentWillReceiveProps` changed to return Promises because by having access to `this.props` and also `nextProps` as an argument, it helps in deciding whether a data fetch is really necessary.

**Comment by Satyam** [comment]
Actually, I think I have a sort of middle ground here.  When using [`renderToString`](https://github.com/Satyam/preact-async/blob/master/webServer/uwa.jsx#L9) the rendering process effectively pauses while the data is fetched and it does get into the HTML.  My problem there is that somehow, [this line](https://github.com/Satyam/preact-async/blob/master/client/codeSplit/loadAsync.jsx#L13) doesn't render the imported stateless component but the result of `toString`.  Anyway, this is besides the point.

When rendering on the client side, it would be acceptable for the render **not** to be paused.  However, it is important that the components get re-rendered with the newly received data.  This is no problem when using Redux, as any change in the data store would trigger such a re-render, but there is no Redux in [this example](https://github.com/Satyam/preact-async/blob/master/client/codeSplit/loadAsync.jsx) to do it.  Moreover, it would be important that the re-render be queued once **all** the requested data arrives, to avoid pointless intermediate states. Stateful components might chain a `forceUpdate` at the end of the Promise, but that would be inefficient as each Promise resolved would trigger a new re-render.  

So, my suggested behaviour is:

- with `renderToString`: pause until Promise resolved (it already does so)
- with `render`: keep going but queue a re-render of all the components involved when all the Promises get resolved.

**Comment by robertknight** [comment]
Given that React now has an official API for loading components lazily ([Suspense](https://reactjs.org/docs/react-api.html#suspense)), perhaps we should close this issue in favour of one for implementing an API compatible with `React.lazy`?

**Comment by developit** [comment]
Agreed @robertknight. We have support for Suspense-based deferred hydration and tree creation landing in #2291 / #2214 and that will likely be the most logical path forward here. It avoids the pitfalls mentioned in this thread relating to deadlocked async trees, and doesn't rely on the renderer dealing with concurrent asynchronous trees.
