### ISSUE TITLE
Post-mount with componentDidMount

### ISSUE THREAD

**Issue by ustccjw** [preactjs/preact#648]
#In 8.1.0, componentDidMount/componentDidUpdate can not promise to be called after dom mount/update.

related resource: https://developmentarc.gitbooks.io/react-indepth/content/life_cycle/birth/post_mount_with_component_did_mount.html

related PR:
https://github.com/developit/preact/pull/506#issuecomment-293879820

**Comment by developit** [comment]
@ustccjw would you be able to put together a jsfiddle that shows the ordering issue?  I'm not sure I understand the problem.

**Comment by ustccjw** [comment]
demo: https://jsfiddle.net/ustccjw/uzyh4r01/1/

when you click update button，child `componentDidUpdate` will execute before parent DOM update.

**Comment by robertknight** [comment]
I'll describe the issue as I understand it. Given this component tree:

```
Parent
   |
   Child
```

In Preact 8.1.0, triggering an update on `Parent` which re-renders both `Parent` and `Child` will result in the child's `componentDidUpdate` callback being triggered _after_ the `Child`'s DOM has updated but _before_ the `Parent`'s DOM has been updated.

React on the other hand queues both `componentDidMount` and `componentDidUpdate` callbacks and executes them all once the entire tree has been updated ([in the Fiber renderer](https://github.com/facebook/react/blob/master/src/renderers/shared/fiber/ReactFiberScheduler.js#L509), [in the stack Renderer](https://github.com/facebook/react/blob/master/src/renderers/dom/stack/client/ReactReconcileTransaction.js#L67)).

The [componentDidUpdate](https://facebook.github.io/react/docs/react-component.html#componentdidupdate) docs don't specify this behaviour, but if the child runs code in `componentDidUpdate` which might be invalidated by the parent's update in any way (eg. accessing the parent directly, measuring the child's own size) then the result will be wrong unless the child's `componentDidUpdate` is deferred until the whole tree is updated.

I suggest that in Preact we queue `componentDidUpdate` callbacks in the same queue that handles mount callbacks and flush them all once the entire tree is updated. I think we deferred doing this last time because it increased the size slightly, but I don't see an easy way around this. Thoughts @developit ?

**Comment by developit** [comment]
I agree. We can work some magic to keep the size down. Maybe this ties into the idea of a more general queue (though we can't really use it as a general callback queue due to size/perf).

**Comment by ustccjw** [comment]
@developit @robertknight Are there any solutions ?

**Comment by developit** [comment]
I haven't had time to dig into this properly yet.  We need a generic "end of work" queue to replace the three specific queues we do now.

**Comment by markselby9** [comment]
Hi, I've just commited a PR trying to solve this issue, along with a test case same as this issue's example. The bundle size slightly increased from 3444->3503 according to 'yarn build'.
Please kindly check and give more thoughts on this, thanks

**Comment by fokusferit** [comment]
So somehow today we also hit this case where componentDidMount() from a Child Component is triggered later and componentDidUpdate() from <Parent> triggered before.

A colleague created a jsfiddle (with console output):

react: https://jsfiddle.net/69z2wepo/213165/
preact: https://jsfiddle.net/3hvru6ex/619/

We hit this when we wanted to start measuring render and call `performance.mark` API.
