### ISSUE TITLE
Provide externs to enable advanced compilation for closure compiler.

### ISSUE THREAD

**Issue by samccone** [preactjs/preact#758]
building off of #564... It would be really helpful if preact shipped an externs file which would enable passing preact.min.js into closure compiler, so that closure compiler would not rename everything.

This would also make preact 100% compatible with closure compiler advanced mode.

--

Further thinking...

It would be great once we had the typings file to then compile the lib and run it again your test suite to make sure it is working.
This will also enforce that the externs are kept up to date since the tests will break otherwise.

**Comment by developit** [comment]
Agreed, I'd like to have CI test both the compiled/minified version and `src`.  As for an externs file, I wonder if it could be based off of the properties listed below and the current library exports?
https://github.com/developit/preact/blob/master/config/properties.json

**Comment by anmonteiro** [comment]
These might be enough: https://github.com/cljsjs/packages/blob/master/preact/resources/cljsjs/preact/common/preact.ext.js

**Comment by developit** [comment]
@anmonteiro nice, looks like a good start. I think we'd want to whitelist `_component` and `__preactattr_` as well, since extensions tend to rely on those from other libraries.

**Comment by smirnowld** [comment]
We're moving to a Preact/Redux stack and have long used Closure Compiler for our custom stack, so we are also interested in setting up advanced compilation step for our new components. 

We took a stab at it and I've made it available under https://github.com/geniussportsgroup/preact-closure-compiler-advanced-optimisations - it's not currently using JSX (thanks to a great example at https://github.com/developit/preact-without-babel !), but it should be possible to set up a babel transpilation step before the compilation step.

We played around with using externs and passing in `preact.min.js` vs not using externs and passing in `preact.min.js` - in both cases the output was 8kb but the former produced 25 warnings vs 17 when not using externs. The end result was the same for us. It would be good to take a look at these warnings.

Hope this will be a helpful example of how to get Preact working with Closure Compiler, and if there's any feedback, we're happy to hear it.

**Comment by mk0x9** [comment]
@smirnowld that repo is dead :( Do you still have it somewhere?

**Comment by smirnowld** [comment]
I'm sorry, I don't. We had to ditch our hope of using Closure compiler with Preact. I can't recommend Closure Compiler any more to be honest as it's a lot of work to make sure it works (especially if you have a quirky set up), the learning curve is steep, documentation is lacking, and the community isn't large enough. While there is currently no match for Closure Compiler's capabilities, truth is, for most applications such level of optimisations is not needed, and using something much simpler like Webpack or Rollup gets you far enough and keeps developers sane and happy with the tools they use.

**Comment by mk0x9** [comment]
Oh, no problem, I spent some time already with GCJ. :)

I want to try experiment with first approach, as outlined here: https://github.com/facebook/react/issues/11092#issuecomment-351727335, given small preact core size.

**Comment by marvinhagemeister** [comment]
Looks like there isn't much interest in adding an externs file. We're happy to review any PRs for that if somebody wants to pick this up :+1:

**Comment by coetry** [comment]
Does this repo: https://github.com/externs/preact provide the necessary externs to pass through the Closure compiler? I'm really keen on seeing this happen since I would love to use Clojurescript + Preact for a smaller bundle size, yet incredible powerful UI programming model.

**Comment by mbrukman** [comment]
Hi all,

I've been looking to compile apps using Preact with Closure Compiler and ran into the same issue of a lack of Closure Compiler-compatible `@externs` annotations as others here. I've tried multiple tools to convert Preact's TypeScript annotations `index.d.ts` to Closure Compiler-compratible formats, but none of them could parse Preact's `index.d.ts` (possibly because they're quite out-of-date and don't support recent TypeScript constructs).

@coetry — I've looked at  https://github.com/externs/preact, but those types are very generic — e.g., using `Function` or `Object` is fine, but doesn't help provide strong type-safety guarantees that Closure Compiler is able to enforce for you, so you may end up discovering type errors at runtime instead of compile-time, which isn't very helpful.

In the end, I ended up manually transcribing Preact's `index.d.ts` to [Closure Compiler-compatible `@externs` annotations](https://github.com/mbrukman/preact-bazel-closure/blob/master/third_party/preact/v10_4_6/externs/externs.js) for Preact 10.4.6 (since `index.d.ts` hasn't changed for 10.4.7, the externs are also usable as-is for the newer version).

I've tested this with my forks of https://github.com/developit/preact-without-babel and https://github.com/developit/htm (thanks, @developit!) which you can find in the same repo above, under [`//third_party`](https://github.com/mbrukman/preact-bazel-closure/tree/master/third_party).

**Good news:** they work! See instructions for how to build + use them in my repo above.

**Caveats:**

1. I've had to adjust my `@externs` as I more and more of the Preact functionality, so I wouldn't say they're finalized at this time. I'm currently trying to port https://github.com/developit/preact-todomvc to use the same Preact + Bazel + Closure framework, and it doesn't quite work yet, so it's possible I will need to adjust my `@externs` definitions yet again.

2. You'll find that type annotations for JSX are notably missing. That's an intentional omission for me, because I specifically don't plan to use JSX<sup>1</sup>. Since Closure Compiler doesn't support JSX, I'm guessing they're also not necessary, because Closure Compiler will never see JSX (they will have been transpiled before Closure Compiler sees the JS). 

**What's next?**

* if Preact maintainers want my copy of the externs file as a starting point to maintain together with the `index.d.ts` file, I'm happy to contribute it to this repo; however, we need some testing to ensure that they don't get out-of-sync, and I don't have any ideas for that
* if anyone is interested in using my externs files in the meantime in their own repos, you're welcome to do so — they're under the same license as Preact itself (MIT) as they're a derivative work

If you have any suggestions / feature requests / bug reports for the externs, feel free to file them on my repo rather than here (at least for now, while they're not maintained here).

---

<sup>1</sup> Why not JSX? I'm looking to build an app with a Go server and JS/TS client, and would like to have a single template language for both, to enable SSR as well as CSR as needed. Thus, I'm hoping to use [Closure Templates](https://github.com/google/closure-templates). My previous plan of using [Metal.js](https://github.com/metal/metal.js) fell through as Metal.js appears to be deprecated, so I'm hoping to get Preact to work with Soy templates (together with Bazel + Closure Compiler, of course!). If anyone has made any progress in this space, or is interested in this as well, let me know!

**Comment by mbrukman** [comment]
Sorry, folks, I have to add a significant caveat to my [earlier enthusiastic comment](https://github.com/preactjs/preact/issues/758#issuecomment-682655051), as I recently discovered why I've been having issues defining Closure externs for Preact: it turns out that Closure Compiler does not support combining `@typedef` with `@template` in a single declaration, which as you can imagine, is quite limiting.

For more details, see https://github.com/google/closure-compiler/issues/890 (from 2015) and specifically [my comment on that issue](https://github.com/google/closure-compiler/issues/890#issuecomment-683375473) — until that's addressed, I'm not sure how to actually make a faithful representation of Preact's types in a Closure-Compiler-compatible `@externs` file.

I'll also note that while what is [checked in in my repo](https://github.com/mbrukman/preact-bazel-closure) currently _does_ compile and work for my limited use cases (with no warnings or errors from Bazel<sup>1</sup>), upgrading the version of https://github.com/bazelbuild/rules_closure in my `WORKSPACE` from v0.10.0 to a later commit:

```diff
diff --git a/WORKSPACE b/WORKSPACE
index 0829eef..abd47c2 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -12,16 +12,12 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.

-load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
+load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

-http_archive(
+git_repository(
     name = "io_bazel_rules_closure",
-    sha256 = "7d206c2383811f378a5ef03f4aacbcf5f47fd8650f6abbc3fa89f3a27dd8b176",
-    strip_prefix = "rules_closure-0.10.0",
-    urls = [
-        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
-        "https://github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
-    ],
+    remote = "https://github.com/bazelbuild/rules_closure.git",
+    commit = "62746bdd1087c1198a81143e7d8ef3d144a43c0f",
 )

 load("@io_bazel_rules_closure//closure:repositories.bzl", "rules_closure_dependencies", "rules_closure_toolchains")
```

fails with the following errors in the output:

```
third_party/preact/v10_4_6/externs/externs.js:190: ERROR - Bad type annotation. Unknown type P
/** @typedef {preact.ComponentClass<P> | preact.FunctionComponent<P>} */
                                    ^
  ProTip: "JSC_UNRECOGNIZED_TYPE_ERROR" or "checkTypes" or "unrecognizedTypeError" can be added to the `suppress` attribute of:
  //third_party/preact/v10_4_6/externs:externs
  Alternatively /** @suppress {checkTypes} */ can be added to the source file.

third_party/preact/v10_4_6/externs/externs.js:190: ERROR - Bad type annotation. Unknown type P
/** @typedef {preact.ComponentClass<P> | preact.FunctionComponent<P>} */
                                                                  ^
  ProTip: "JSC_UNRECOGNIZED_TYPE_ERROR" or "checkTypes" or "unrecognizedTypeError" can be added to the `suppress` attribute of:
  //third_party/preact/v10_4_6/externs:externs
  Alternatively /** @suppress {checkTypes} */ can be added to the source file.

third_party/preact/v10_4_6/externs/externs.js:195: ERROR - Bad type annotation. Unknown type P
/** @typedef {preact.ComponentType<P>} */
                                   ^
  ProTip: "JSC_UNRECOGNIZED_TYPE_ERROR" or "checkTypes" or "unrecognizedTypeError" can be added to the `suppress` attribute of:
  //third_party/preact/v10_4_6/externs:externs
  Alternatively /** @suppress {checkTypes} */ can be added to the source file.

third_party/preact/v10_4_6/externs/externs.js:232: ERROR - preact.FunctionalComponent cannot extend this type; interfaces can only extend interfaces
preact.FunctionalComponent = class { };
                             ^
  ProTip: "JSC_CONFLICTING_EXTENDED_TYPE" or "checkTypes" can be added to the `suppress` attribute of:
  //third_party/preact/v10_4_6/externs:externs
  Alternatively /** @suppress {checkTypes} */ can be added to the source file.

third_party/preact/v10_4_6/externs/externs.js:289: ERROR - Bad type annotation. Unknown type P
 * @type {preact.FunctionComponent<P> | preact.Component<P, S>}
                                   ^
  ProTip: "JSC_UNRECOGNIZED_TYPE_ERROR" or "checkTypes" or "unrecognizedTypeError" can be added to the `suppress` attribute of:
  //third_party/preact/v10_4_6/externs:externs
  Alternatively /** @suppress {checkTypes} */ can be added to the source file.

third_party/preact/v10_4_6/externs/externs.js:289: ERROR - Bad type annotation. Unknown type P
 * @type {preact.FunctionComponent<P> | preact.Component<P, S>}
                                                         ^
  ProTip: "JSC_UNRECOGNIZED_TYPE_ERROR" or "checkTypes" or "unrecognizedTypeError" can be added to the `suppress` attribute of:
  //third_party/preact/v10_4_6/externs:externs
  Alternatively /** @suppress {checkTypes} */ can be added to the source file.

third_party/preact/v10_4_6/externs/externs.js:289: ERROR - Bad type annotation. Unknown type S
 * @type {preact.FunctionComponent<P> | preact.Component<P, S>}
                                                            ^
  ProTip: "JSC_UNRECOGNIZED_TYPE_ERROR" or "checkTypes" or "unrecognizedTypeError" can be added to the `suppress` attribute of:
  //third_party/preact/v10_4_6/externs:externs
  Alternatively /** @suppress {checkTypes} */ can be added to the source file.

7 error(s), 0 warning(s), 94.5% typed

INFO: Elapsed time: 332.189s, Critical Path: 124.28s
INFO: 192 processes: 178 darwin-sandbox, 14 worker.
FAILED: Build did NOT complete successfully
```

which points to the incompatibility of `@typedef` + `@typedef` I mentioned above.

---

<sup>1</sup> It appears that Bazel has been swallowing Closure Compiler errors for me, because running Closure Compiler directly on this input shows the same messages as warnings (not errors), but since I've been using Closure Compiler via Bazel, I haven't seen them.
